# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from resource.store import store_pb2 as resource_dot_store_dot_store__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resource/store/store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveObject = channel.unary_unary(
                '/resource.store.Service/SaveObject',
                request_serializer=resource_dot_store_dot_store__pb2.SaveObjectRequest.SerializeToString,
                response_deserializer=resource_dot_store_dot_store__pb2.SaveObjectResponse.FromString,
                _registered_method=True)
        self.SaveStreamChunk = channel.unary_unary(
                '/resource.store.Service/SaveStreamChunk',
                request_serializer=resource_dot_store_dot_store__pb2.SaveStreamChunkRequest.SerializeToString,
                response_deserializer=resource_dot_store_dot_store__pb2.SaveStreamChunkResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/resource.store.Service/GetObject',
                request_serializer=resource_dot_store_dot_store__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=resource_dot_store_dot_store__pb2.GetObjectResponse.FromString,
                _registered_method=True)
        self.GetStreamChunk = channel.unary_unary(
                '/resource.store.Service/GetStreamChunk',
                request_serializer=resource_dot_store_dot_store__pb2.GetStreamChunkRequest.SerializeToString,
                response_deserializer=resource_dot_store_dot_store__pb2.GetStreamChunkResponse.FromString,
                _registered_method=True)
        self.GetID = channel.unary_unary(
                '/resource.store.Service/GetID',
                request_serializer=resource_dot_store_dot_store__pb2.GetIDRequest.SerializeToString,
                response_deserializer=resource_dot_store_dot_store__pb2.GetIDResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveStreamChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveObject': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveObject,
                    request_deserializer=resource_dot_store_dot_store__pb2.SaveObjectRequest.FromString,
                    response_serializer=resource_dot_store_dot_store__pb2.SaveObjectResponse.SerializeToString,
            ),
            'SaveStreamChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveStreamChunk,
                    request_deserializer=resource_dot_store_dot_store__pb2.SaveStreamChunkRequest.FromString,
                    response_serializer=resource_dot_store_dot_store__pb2.SaveStreamChunkResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=resource_dot_store_dot_store__pb2.GetObjectRequest.FromString,
                    response_serializer=resource_dot_store_dot_store__pb2.GetObjectResponse.SerializeToString,
            ),
            'GetStreamChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamChunk,
                    request_deserializer=resource_dot_store_dot_store__pb2.GetStreamChunkRequest.FromString,
                    response_serializer=resource_dot_store_dot_store__pb2.GetStreamChunkResponse.SerializeToString,
            ),
            'GetID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetID,
                    request_deserializer=resource_dot_store_dot_store__pb2.GetIDRequest.FromString,
                    response_serializer=resource_dot_store_dot_store__pb2.GetIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resource.store.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resource.store.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.store.Service/SaveObject',
            resource_dot_store_dot_store__pb2.SaveObjectRequest.SerializeToString,
            resource_dot_store_dot_store__pb2.SaveObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveStreamChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.store.Service/SaveStreamChunk',
            resource_dot_store_dot_store__pb2.SaveStreamChunkRequest.SerializeToString,
            resource_dot_store_dot_store__pb2.SaveStreamChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.store.Service/GetObject',
            resource_dot_store_dot_store__pb2.GetObjectRequest.SerializeToString,
            resource_dot_store_dot_store__pb2.GetObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.store.Service/GetStreamChunk',
            resource_dot_store_dot_store__pb2.GetStreamChunkRequest.SerializeToString,
            resource_dot_store_dot_store__pb2.GetStreamChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.store.Service/GetID',
            resource_dot_store_dot_store__pb2.GetIDRequest.SerializeToString,
            resource_dot_store_dot_store__pb2.GetIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
