# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x06logger\"\xf1\x01\n\x0ePushLogRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontainer_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontainer_type\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x32\n\x06labels\x18\x07 \x03(\x0b\x32\".logger.PushLogRequest.LabelsEntry\x12\x0b\n\x03raw\x18\x08 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x14PushLogsBatchRequest\x12$\n\x04logs\x18\x01 \x03(\x0b\x32\x16.logger.PushLogRequest\"c\n\x0fPushLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63\x63\x65pted_count\x18\x03 \x01(\x05\x12\x16\n\x0erejected_count\x18\x04 \x01(\x05\x32\xd1\x01\n\nLogService\x12:\n\x07PushLog\x12\x16.logger.PushLogRequest\x1a\x17.logger.PushLogResponse\x12\x46\n\rPushLogsBatch\x12\x1c.logger.PushLogsBatchRequest\x1a\x17.logger.PushLogResponse\x12?\n\nStreamLogs\x12\x16.logger.PushLogRequest\x1a\x17.logger.PushLogResponse(\x01\x42(Z&github.com/9triver/iarnet/proto/loggerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/9triver/iarnet/proto/logger'
  _globals['_PUSHLOGREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_PUSHLOGREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_PUSHLOGREQUEST']._serialized_start=25
  _globals['_PUSHLOGREQUEST']._serialized_end=266
  _globals['_PUSHLOGREQUEST_LABELSENTRY']._serialized_start=221
  _globals['_PUSHLOGREQUEST_LABELSENTRY']._serialized_end=266
  _globals['_PUSHLOGSBATCHREQUEST']._serialized_start=268
  _globals['_PUSHLOGSBATCHREQUEST']._serialized_end=328
  _globals['_PUSHLOGRESPONSE']._serialized_start=330
  _globals['_PUSHLOGRESPONSE']._serialized_end=429
  _globals['_LOGSERVICE']._serialized_start=432
  _globals['_LOGSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
