# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logger_pb2 as logger__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogServiceStub(object):
    """LogService 日志服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushLog = channel.unary_unary(
                '/logger.LogService/PushLog',
                request_serializer=logger__pb2.PushLogRequest.SerializeToString,
                response_deserializer=logger__pb2.PushLogResponse.FromString,
                _registered_method=True)
        self.PushLogsBatch = channel.unary_unary(
                '/logger.LogService/PushLogsBatch',
                request_serializer=logger__pb2.PushLogsBatchRequest.SerializeToString,
                response_deserializer=logger__pb2.PushLogResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/logger.LogService/StreamLogs',
                request_serializer=logger__pb2.PushLogRequest.SerializeToString,
                response_deserializer=logger__pb2.PushLogResponse.FromString,
                _registered_method=True)


class LogServiceServicer(object):
    """LogService 日志服务
    """

    def PushLog(self, request, context):
        """PushLogs 推送日志（单条）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushLogsBatch(self, request, context):
        """PushLogsBatch 批量推送日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """StreamLogs 流式推送日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushLog': grpc.unary_unary_rpc_method_handler(
                    servicer.PushLog,
                    request_deserializer=logger__pb2.PushLogRequest.FromString,
                    response_serializer=logger__pb2.PushLogResponse.SerializeToString,
            ),
            'PushLogsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PushLogsBatch,
                    request_deserializer=logger__pb2.PushLogsBatchRequest.FromString,
                    response_serializer=logger__pb2.PushLogResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=logger__pb2.PushLogRequest.FromString,
                    response_serializer=logger__pb2.PushLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logger.LogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logger.LogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogService(object):
    """LogService 日志服务
    """

    @staticmethod
    def PushLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.LogService/PushLog',
            logger__pb2.PushLogRequest.SerializeToString,
            logger__pb2.PushLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushLogsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.LogService/PushLogsBatch',
            logger__pb2.PushLogsBatchRequest.SerializeToString,
            logger__pb2.PushLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/logger.LogService/StreamLogs',
            logger__pb2.PushLogRequest.SerializeToString,
            logger__pb2.PushLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
