# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\x12\x04peer\"x\n\x0cProviderInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\x05\x12\x14\n\x0cpeer_address\x18\x07 \x01(\t\"&\n\x0f\x45xchangeRequest\x12\x13\n\x0bknown_peers\x18\x01 \x03(\t\"\'\n\x10\x45xchangeResponse\x12\x13\n\x0bknown_peers\x18\x01 \x03(\t\"@\n\x17ProviderExchangeRequest\x12%\n\tproviders\x18\x01 \x03(\x0b\x32\x12.peer.ProviderInfo\"A\n\x18ProviderExchangeResponse\x12%\n\tproviders\x18\x01 \x03(\x0b\x32\x12.peer.ProviderInfo\"K\n\x13ProviderCallRequest\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"F\n\x14ProviderCallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x32\xe8\x01\n\x0bPeerService\x12>\n\rExchangePeers\x12\x15.peer.ExchangeRequest\x1a\x16.peer.ExchangeResponse\x12R\n\x11\x45xchangeProviders\x12\x1d.peer.ProviderExchangeRequest\x1a\x1e.peer.ProviderExchangeResponse\x12\x45\n\x0c\x43\x61llProvider\x12\x19.peer.ProviderCallRequest\x1a\x1a.peer.ProviderCallResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_PROVIDERINFO']._serialized_start=20
  _globals['_PROVIDERINFO']._serialized_end=140
  _globals['_EXCHANGEREQUEST']._serialized_start=142
  _globals['_EXCHANGEREQUEST']._serialized_end=180
  _globals['_EXCHANGERESPONSE']._serialized_start=182
  _globals['_EXCHANGERESPONSE']._serialized_end=221
  _globals['_PROVIDEREXCHANGEREQUEST']._serialized_start=223
  _globals['_PROVIDEREXCHANGEREQUEST']._serialized_end=287
  _globals['_PROVIDEREXCHANGERESPONSE']._serialized_start=289
  _globals['_PROVIDEREXCHANGERESPONSE']._serialized_end=354
  _globals['_PROVIDERCALLREQUEST']._serialized_start=356
  _globals['_PROVIDERCALLREQUEST']._serialized_end=431
  _globals['_PROVIDERCALLRESPONSE']._serialized_start=433
  _globals['_PROVIDERCALLRESPONSE']._serialized_end=503
  _globals['_PEERSERVICE']._serialized_start=506
  _globals['_PEERSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
