// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: store/store.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_LANGUAGE_UNKNOWN Language = 0
	Language_LANGUAGE_JSON    Language = 1
	Language_LANGUAGE_GO      Language = 2
	Language_LANGUAGE_PYTHON  Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNKNOWN",
		1: "LANGUAGE_JSON",
		2: "LANGUAGE_GO",
		3: "LANGUAGE_PYTHON",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNKNOWN": 0,
		"LANGUAGE_JSON":    1,
		"LANGUAGE_GO":      2,
		"LANGUAGE_PYTHON":  3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_store_store_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_store_store_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{0}
}

type ObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_store_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectRef) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ObjectRef) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// EncodedObject stores a byte encoded object
type EncodedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                                  // if returned from ipc call, id won't be set
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`                              // serialized object data, or nil if current object is a stream
	Language      Language               `protobuf:"varint,3,opt,name=Language,proto3,enum=store.Language" json:"Language,omitempty"` // if is JSON, it can be decoded to either Go, Python, or else it can only be decoded to corresponding language.
	IsStream      bool                   `protobuf:"varint,4,opt,name=IsStream,proto3" json:"IsStream,omitempty"`                     // mark if the object is a stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedObject) Reset() {
	*x = EncodedObject{}
	mi := &file_store_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedObject) ProtoMessage() {}

func (x *EncodedObject) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedObject.ProtoReflect.Descriptor instead.
func (*EncodedObject) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedObject) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EncodedObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodedObject) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNKNOWN
}

func (x *EncodedObject) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectID      string                 `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Offset        string                 `protobuf:"bytes,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	EoS           bool                   `protobuf:"varint,3,opt,name=EoS,proto3" json:"EoS,omitempty"`
	Value         *EncodedObject         `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_store_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChunk) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *StreamChunk) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *StreamChunk) GetEoS() bool {
	if x != nil {
		return x.EoS
	}
	return false
}

func (x *StreamChunk) GetValue() *EncodedObject {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *EncodedObject         `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveObjectRequest) Reset() {
	*x = SaveObjectRequest{}
	mi := &file_store_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectRequest) ProtoMessage() {}

func (x *SaveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectRequest.ProtoReflect.Descriptor instead.
func (*SaveObjectRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *SaveObjectRequest) GetObject() *EncodedObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type SaveObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     *ObjectRef             `protobuf:"bytes,1,opt,name=ObjectRef,proto3" json:"ObjectRef,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveObjectResponse) Reset() {
	*x = SaveObjectResponse{}
	mi := &file_store_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectResponse) ProtoMessage() {}

func (x *SaveObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectResponse.ProtoReflect.Descriptor instead.
func (*SaveObjectResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *SaveObjectResponse) GetObjectRef() *ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

func (x *SaveObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     *ObjectRef             `protobuf:"bytes,1,opt,name=ObjectRef,proto3" json:"ObjectRef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_store_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectRequest) GetObjectRef() *ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *EncodedObject         `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_store_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectResponse) GetObject() *EncodedObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type GetStreamChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectID      string                 `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Offset        string                 `protobuf:"bytes,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamChunkRequest) Reset() {
	*x = GetStreamChunkRequest{}
	mi := &file_store_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamChunkRequest) ProtoMessage() {}

func (x *GetStreamChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamChunkRequest.ProtoReflect.Descriptor instead.
func (*GetStreamChunkRequest) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{7}
}

func (x *GetStreamChunkRequest) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *GetStreamChunkRequest) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type GetStreamChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *StreamChunk           `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamChunkResponse) Reset() {
	*x = GetStreamChunkResponse{}
	mi := &file_store_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamChunkResponse) ProtoMessage() {}

func (x *GetStreamChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamChunkResponse.ProtoReflect.Descriptor instead.
func (*GetStreamChunkResponse) Descriptor() ([]byte, []int) {
	return file_store_store_proto_rawDescGZIP(), []int{8}
}

func (x *GetStreamChunkResponse) GetChunk() *StreamChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_store_store_proto protoreflect.FileDescriptor

const file_store_store_proto_rawDesc = "" +
	"\n" +
	"\x11store/store.proto\x12\x05store\"3\n" +
	"\tObjectRef\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\"|\n" +
	"\rEncodedObject\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12+\n" +
	"\bLanguage\x18\x03 \x01(\x0e2\x0f.store.LanguageR\bLanguage\x12\x1a\n" +
	"\bIsStream\x18\x04 \x01(\bR\bIsStream\"\x95\x01\n" +
	"\vStreamChunk\x12\x1a\n" +
	"\bObjectID\x18\x01 \x01(\tR\bObjectID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\tR\x06Offset\x12\x10\n" +
	"\x03EoS\x18\x03 \x01(\bR\x03EoS\x12*\n" +
	"\x05Value\x18\x04 \x01(\v2\x14.store.EncodedObjectR\x05Value\x12\x14\n" +
	"\x05Error\x18\x05 \x01(\tR\x05Error\"A\n" +
	"\x11SaveObjectRequest\x12,\n" +
	"\x06Object\x18\x01 \x01(\v2\x14.store.EncodedObjectR\x06Object\"t\n" +
	"\x12SaveObjectResponse\x12.\n" +
	"\tObjectRef\x18\x01 \x01(\v2\x10.store.ObjectRefR\tObjectRef\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"B\n" +
	"\x10GetObjectRequest\x12.\n" +
	"\tObjectRef\x18\x01 \x01(\v2\x10.store.ObjectRefR\tObjectRef\"A\n" +
	"\x11GetObjectResponse\x12,\n" +
	"\x06Object\x18\x01 \x01(\v2\x14.store.EncodedObjectR\x06Object\"K\n" +
	"\x15GetStreamChunkRequest\x12\x1a\n" +
	"\bObjectID\x18\x01 \x01(\tR\bObjectID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\tR\x06Offset\"B\n" +
	"\x16GetStreamChunkResponse\x12(\n" +
	"\x05Chunk\x18\x01 \x01(\v2\x12.store.StreamChunkR\x05Chunk*Y\n" +
	"\bLanguage\x12\x14\n" +
	"\x10LANGUAGE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rLANGUAGE_JSON\x10\x01\x12\x0f\n" +
	"\vLANGUAGE_GO\x10\x02\x12\x13\n" +
	"\x0fLANGUAGE_PYTHON\x10\x032\xdb\x01\n" +
	"\aService\x12A\n" +
	"\n" +
	"SaveObject\x12\x18.store.SaveObjectRequest\x1a\x19.store.SaveObjectResponse\x12>\n" +
	"\tGetObject\x12\x17.store.GetObjectRequest\x1a\x18.store.GetObjectResponse\x12M\n" +
	"\x0eGetStreamChunk\x12\x1c.store.GetStreamChunkRequest\x1a\x1d.store.GetStreamChunkResponseB9Z7github.com/9triver/iarnet/internal/proto/resource/storeb\x06proto3"

var (
	file_store_store_proto_rawDescOnce sync.Once
	file_store_store_proto_rawDescData []byte
)

func file_store_store_proto_rawDescGZIP() []byte {
	file_store_store_proto_rawDescOnce.Do(func() {
		file_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)))
	})
	return file_store_store_proto_rawDescData
}

var file_store_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_store_store_proto_goTypes = []any{
	(Language)(0),                  // 0: store.Language
	(*ObjectRef)(nil),              // 1: store.ObjectRef
	(*EncodedObject)(nil),          // 2: store.EncodedObject
	(*StreamChunk)(nil),            // 3: store.StreamChunk
	(*SaveObjectRequest)(nil),      // 4: store.SaveObjectRequest
	(*SaveObjectResponse)(nil),     // 5: store.SaveObjectResponse
	(*GetObjectRequest)(nil),       // 6: store.GetObjectRequest
	(*GetObjectResponse)(nil),      // 7: store.GetObjectResponse
	(*GetStreamChunkRequest)(nil),  // 8: store.GetStreamChunkRequest
	(*GetStreamChunkResponse)(nil), // 9: store.GetStreamChunkResponse
}
var file_store_store_proto_depIdxs = []int32{
	0,  // 0: store.EncodedObject.Language:type_name -> store.Language
	2,  // 1: store.StreamChunk.Value:type_name -> store.EncodedObject
	2,  // 2: store.SaveObjectRequest.Object:type_name -> store.EncodedObject
	1,  // 3: store.SaveObjectResponse.ObjectRef:type_name -> store.ObjectRef
	1,  // 4: store.GetObjectRequest.ObjectRef:type_name -> store.ObjectRef
	2,  // 5: store.GetObjectResponse.Object:type_name -> store.EncodedObject
	3,  // 6: store.GetStreamChunkResponse.Chunk:type_name -> store.StreamChunk
	4,  // 7: store.Service.SaveObject:input_type -> store.SaveObjectRequest
	6,  // 8: store.Service.GetObject:input_type -> store.GetObjectRequest
	8,  // 9: store.Service.GetStreamChunk:input_type -> store.GetStreamChunkRequest
	5,  // 10: store.Service.SaveObject:output_type -> store.SaveObjectResponse
	7,  // 11: store.Service.GetObject:output_type -> store.GetObjectResponse
	9,  // 12: store.Service.GetStreamChunk:output_type -> store.GetStreamChunkResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_store_store_proto_init() }
func file_store_store_proto_init() {
	if File_store_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_store_proto_rawDesc), len(file_store_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_store_proto_goTypes,
		DependencyIndexes: file_store_store_proto_depIdxs,
		EnumInfos:         file_store_store_proto_enumTypes,
		MessageInfos:      file_store_store_proto_msgTypes,
	}.Build()
	File_store_store_proto = out.File
	file_store_store_proto_goTypes = nil
	file_store_store_proto_depIdxs = nil
}
