# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ignis/actor/actor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ignis/actor/actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import types_pb2 as common_dot_types__pb2
from common import messages_pb2 as common_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ignis/actor/actor.proto\x12\x0bignis.actor\x1a\x12\x63ommon/types.proto\x1a\x15\x63ommon/messages.proto\"y\n\x08\x46unction\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0e\n\x06Params\x18\x02 \x03(\t\x12\x14\n\x0cRequirements\x18\x03 \x03(\t\x12\x15\n\rPickledObject\x18\x04 \x01(\x0c\x12\"\n\x08Language\x18\x05 \x01(\x0e\x32\x10.common.Language\"<\n\tInvokeArg\x12\r\n\x05Param\x18\x01 \x01(\t\x12 \n\x05Value\x18\x02 \x01(\x0b\x32\x11.common.ObjectRef\"H\n\rInvokeRequest\x12\x11\n\tRuntimeID\x18\x01 \x01(\t\x12$\n\x04\x41rgs\x18\x02 \x03(\x0b\x32\x16.ignis.actor.InvokeArg\"5\n\tActorInfo\x12\x13\n\x0b\x43\x61lcLatency\x18\x02 \x01(\x03\x12\x13\n\x0bLinkLatency\x18\x03 \x01(\x03\"{\n\x0eInvokeResponse\x12\x11\n\tRuntimeID\x18\x01 \x01(\t\x12!\n\x06Result\x18\x02 \x01(\x0b\x32\x11.common.ObjectRef\x12\r\n\x05\x45rror\x18\x03 \x01(\t\x12$\n\x04Info\x18\x04 \x01(\x0b\x32\x16.ignis.actor.ActorInfo\"\x8f\x02\n\x07Message\x12&\n\x04Type\x18\x01 \x01(\x0e\x32\x18.ignis.actor.MessageType\x12\x1a\n\x03\x41\x63k\x18\x02 \x01(\x0b\x32\x0b.common.AckH\x00\x12\x1e\n\x05Ready\x18\x03 \x01(\x0b\x32\r.common.ReadyH\x00\x12)\n\x08\x46unction\x18\x04 \x01(\x0b\x32\x15.ignis.actor.FunctionH\x00\x12\x33\n\rInvokeRequest\x18\x05 \x01(\x0b\x32\x1a.ignis.actor.InvokeRequestH\x00\x12\x35\n\x0eInvokeResponse\x18\x06 \x01(\x0b\x32\x1b.ignis.actor.InvokeResponseH\x00\x42\t\n\x07Message*i\n\x0bMessageType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08\x46UNCTION\x10\x03\x12\x12\n\x0eINVOKE_REQUEST\x10\x04\x12\x13\n\x0fINVOKE_RESPONSE\x10\x05\x42\x36Z4github.com/9triver/iarnet/internal/proto/ignis/actorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ignis.actor.actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/9triver/iarnet/internal/proto/ignis/actor'
  _globals['_MESSAGETYPE']._serialized_start=796
  _globals['_MESSAGETYPE']._serialized_end=901
  _globals['_FUNCTION']._serialized_start=83
  _globals['_FUNCTION']._serialized_end=204
  _globals['_INVOKEARG']._serialized_start=206
  _globals['_INVOKEARG']._serialized_end=266
  _globals['_INVOKEREQUEST']._serialized_start=268
  _globals['_INVOKEREQUEST']._serialized_end=340
  _globals['_ACTORINFO']._serialized_start=342
  _globals['_ACTORINFO']._serialized_end=395
  _globals['_INVOKERESPONSE']._serialized_start=397
  _globals['_INVOKERESPONSE']._serialized_end=520
  _globals['_MESSAGE']._serialized_start=523
  _globals['_MESSAGE']._serialized_end=794
# @@protoc_insertion_point(module_scope)
