// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: resource/provider/provider.proto

package provider

import (
	resource "github.com/9triver/iarnet/internal/proto/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderType) Reset() {
	*x = ProviderType{}
	mi := &file_resource_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderType) ProtoMessage() {}

func (x *ProviderType) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderType.ProtoReflect.Descriptor instead.
func (*ProviderType) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ProviderType  *ProviderType          `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConnectResponse) GetProviderType() *ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return nil
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // 可选的 provider_id，用于鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *GetCapacityRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      *resource.Capacity     `protobuf:"bytes,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{4}
}

func (x *GetCapacityResponse) GetCapacity() *resource.Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type GetAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // 可选的 provider_id，用于鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableRequest) Reset() {
	*x = GetAvailableRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableRequest) ProtoMessage() {}

func (x *GetAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     *resource.Info         `protobuf:"bytes,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableResponse) Reset() {
	*x = GetAvailableResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableResponse) ProtoMessage() {}

func (x *GetAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableResponse) GetAvailable() *resource.Info {
	if x != nil {
		return x.Available
	}
	return nil
}

type DeployRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceId      string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ResourceRequest *resource.Info         `protobuf:"bytes,3,opt,name=resource_request,json=resourceRequest,proto3" json:"resource_request,omitempty"`
	EnvVars         map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProviderId      string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // 可选的 provider_id，用于鉴权
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *DeployRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeployRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployRequest) GetResourceRequest() *resource.Info {
	if x != nil {
		return x.ResourceRequest
	}
	return nil
}

func (x *DeployRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DeployRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{8}
}

func (x *DeployResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // 可选的 provider_id，用于鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// ResourceTags 资源标签（描述 provider 支持的计算资源类型）
type ResourceTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           bool                   `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // 是否支持 CPU
	Gpu           bool                   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`       // 是否支持 GPU
	Memory        bool                   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"` // 是否支持内存
	Camera        bool                   `protobuf:"varint,4,opt,name=camera,proto3" json:"camera,omitempty"` // 是否支持摄像头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTags) Reset() {
	*x = ResourceTags{}
	mi := &file_resource_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTags) ProtoMessage() {}

func (x *ResourceTags) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTags.ProtoReflect.Descriptor instead.
func (*ResourceTags) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceTags) GetCpu() bool {
	if x != nil {
		return x.Cpu
	}
	return false
}

func (x *ResourceTags) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *ResourceTags) GetMemory() bool {
	if x != nil {
		return x.Memory
	}
	return false
}

func (x *ResourceTags) GetCamera() bool {
	if x != nil {
		return x.Camera
	}
	return false
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      *resource.Capacity     `protobuf:"bytes,1,opt,name=capacity,proto3" json:"capacity,omitempty"`                             // 当前资源使用情况（总容量、已使用、可用）
	ResourceTags  *ResourceTags          `protobuf:"bytes,2,opt,name=resource_tags,json=resourceTags,proto3" json:"resource_tags,omitempty"` // 所具有的资源类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetCapacity() *resource.Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *HealthCheckResponse) GetResourceTags() *ResourceTags {
	if x != nil {
		return x.ResourceTags
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_resource_provider_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{12}
}

func (x *DisconnectRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_resource_provider_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_resource_provider_provider_proto_rawDescGZIP(), []int{13}
}

var File_resource_provider_provider_proto protoreflect.FileDescriptor

const file_resource_provider_provider_proto_rawDesc = "" +
	"\n" +
	" resource/provider/provider.proto\x12\bprovider\x1a\x17resource/resource.proto\"\"\n" +
	"\fProviderType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x0eConnectRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"~\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12;\n" +
	"\rprovider_type\x18\x03 \x01(\v2\x16.provider.ProviderTypeR\fproviderType\"5\n" +
	"\x12GetCapacityRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"E\n" +
	"\x13GetCapacityResponse\x12.\n" +
	"\bcapacity\x18\x01 \x01(\v2\x12.resource.CapacityR\bcapacity\"6\n" +
	"\x13GetAvailableRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"D\n" +
	"\x14GetAvailableResponse\x12,\n" +
	"\tavailable\x18\x01 \x01(\v2\x0e.resource.InfoR\tavailable\"\x9f\x02\n" +
	"\rDeployRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x129\n" +
	"\x10resource_request\x18\x03 \x01(\v2\x0e.resource.InfoR\x0fresourceRequest\x12?\n" +
	"\benv_vars\x18\x04 \x03(\v2$.provider.DeployRequest.EnvVarsEntryR\aenvVars\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eDeployResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"5\n" +
	"\x12HealthCheckRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"b\n" +
	"\fResourceTags\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\bR\x03cpu\x12\x10\n" +
	"\x03gpu\x18\x02 \x01(\bR\x03gpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\bR\x06memory\x12\x16\n" +
	"\x06camera\x18\x04 \x01(\bR\x06camera\"\x82\x01\n" +
	"\x13HealthCheckResponse\x12.\n" +
	"\bcapacity\x18\x01 \x01(\v2\x12.resource.CapacityR\bcapacity\x12;\n" +
	"\rresource_tags\x18\x02 \x01(\v2\x16.provider.ResourceTagsR\fresourceTags\"4\n" +
	"\x11DisconnectRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"\x14\n" +
	"\x12DisconnectResponse2\xb6\x03\n" +
	"\aService\x12>\n" +
	"\aConnect\x12\x18.provider.ConnectRequest\x1a\x19.provider.ConnectResponse\x12G\n" +
	"\n" +
	"Disconnect\x12\x1b.provider.DisconnectRequest\x1a\x1c.provider.DisconnectResponse\x12J\n" +
	"\vGetCapacity\x12\x1c.provider.GetCapacityRequest\x1a\x1d.provider.GetCapacityResponse\x12M\n" +
	"\fGetAvailable\x12\x1d.provider.GetAvailableRequest\x1a\x1e.provider.GetAvailableResponse\x12;\n" +
	"\x06Deploy\x12\x17.provider.DeployRequest\x1a\x18.provider.DeployResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.provider.HealthCheckRequest\x1a\x1d.provider.HealthCheckResponseB<Z:github.com/9triver/iarnet/internal/proto/resource/providerb\x06proto3"

var (
	file_resource_provider_provider_proto_rawDescOnce sync.Once
	file_resource_provider_provider_proto_rawDescData []byte
)

func file_resource_provider_provider_proto_rawDescGZIP() []byte {
	file_resource_provider_provider_proto_rawDescOnce.Do(func() {
		file_resource_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_provider_provider_proto_rawDesc), len(file_resource_provider_provider_proto_rawDesc)))
	})
	return file_resource_provider_provider_proto_rawDescData
}

var file_resource_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_resource_provider_provider_proto_goTypes = []any{
	(*ProviderType)(nil),         // 0: provider.ProviderType
	(*ConnectRequest)(nil),       // 1: provider.ConnectRequest
	(*ConnectResponse)(nil),      // 2: provider.ConnectResponse
	(*GetCapacityRequest)(nil),   // 3: provider.GetCapacityRequest
	(*GetCapacityResponse)(nil),  // 4: provider.GetCapacityResponse
	(*GetAvailableRequest)(nil),  // 5: provider.GetAvailableRequest
	(*GetAvailableResponse)(nil), // 6: provider.GetAvailableResponse
	(*DeployRequest)(nil),        // 7: provider.DeployRequest
	(*DeployResponse)(nil),       // 8: provider.DeployResponse
	(*HealthCheckRequest)(nil),   // 9: provider.HealthCheckRequest
	(*ResourceTags)(nil),         // 10: provider.ResourceTags
	(*HealthCheckResponse)(nil),  // 11: provider.HealthCheckResponse
	(*DisconnectRequest)(nil),    // 12: provider.DisconnectRequest
	(*DisconnectResponse)(nil),   // 13: provider.DisconnectResponse
	nil,                          // 14: provider.DeployRequest.EnvVarsEntry
	(*resource.Capacity)(nil),    // 15: resource.Capacity
	(*resource.Info)(nil),        // 16: resource.Info
}
var file_resource_provider_provider_proto_depIdxs = []int32{
	0,  // 0: provider.ConnectResponse.provider_type:type_name -> provider.ProviderType
	15, // 1: provider.GetCapacityResponse.capacity:type_name -> resource.Capacity
	16, // 2: provider.GetAvailableResponse.available:type_name -> resource.Info
	16, // 3: provider.DeployRequest.resource_request:type_name -> resource.Info
	14, // 4: provider.DeployRequest.env_vars:type_name -> provider.DeployRequest.EnvVarsEntry
	15, // 5: provider.HealthCheckResponse.capacity:type_name -> resource.Capacity
	10, // 6: provider.HealthCheckResponse.resource_tags:type_name -> provider.ResourceTags
	1,  // 7: provider.Service.Connect:input_type -> provider.ConnectRequest
	12, // 8: provider.Service.Disconnect:input_type -> provider.DisconnectRequest
	3,  // 9: provider.Service.GetCapacity:input_type -> provider.GetCapacityRequest
	5,  // 10: provider.Service.GetAvailable:input_type -> provider.GetAvailableRequest
	7,  // 11: provider.Service.Deploy:input_type -> provider.DeployRequest
	9,  // 12: provider.Service.HealthCheck:input_type -> provider.HealthCheckRequest
	2,  // 13: provider.Service.Connect:output_type -> provider.ConnectResponse
	13, // 14: provider.Service.Disconnect:output_type -> provider.DisconnectResponse
	4,  // 15: provider.Service.GetCapacity:output_type -> provider.GetCapacityResponse
	6,  // 16: provider.Service.GetAvailable:output_type -> provider.GetAvailableResponse
	8,  // 17: provider.Service.Deploy:output_type -> provider.DeployResponse
	11, // 18: provider.Service.HealthCheck:output_type -> provider.HealthCheckResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_resource_provider_provider_proto_init() }
func file_resource_provider_provider_proto_init() {
	if File_resource_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_provider_provider_proto_rawDesc), len(file_resource_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_provider_provider_proto_goTypes,
		DependencyIndexes: file_resource_provider_provider_proto_depIdxs,
		MessageInfos:      file_resource_provider_provider_proto_msgTypes,
	}.Build()
	File_resource_provider_provider_proto = out.File
	file_resource_provider_provider_proto_goTypes = nil
	file_resource_provider_provider_proto_depIdxs = nil
}
