// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: provider/provider.proto

package provider

import (
	resource "github.com/9triver/iarnet/internal/proto/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignIDRequest) Reset() {
	*x = AssignIDRequest{}
	mi := &file_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignIDRequest) ProtoMessage() {}

func (x *AssignIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignIDRequest.ProtoReflect.Descriptor instead.
func (*AssignIDRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *AssignIDRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type AssignIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignIDResponse) Reset() {
	*x = AssignIDResponse{}
	mi := &file_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignIDResponse) ProtoMessage() {}

func (x *AssignIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignIDResponse.ProtoReflect.Descriptor instead.
func (*AssignIDResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *AssignIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{2}
}

type GetCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      *resource.Capacity     `protobuf:"bytes,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *GetCapacityResponse) GetCapacity() *resource.Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type GetAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableRequest) Reset() {
	*x = GetAvailableRequest{}
	mi := &file_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableRequest) ProtoMessage() {}

func (x *GetAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{4}
}

type GetAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     *resource.Info         `protobuf:"bytes,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableResponse) Reset() {
	*x = GetAvailableResponse{}
	mi := &file_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableResponse) ProtoMessage() {}

func (x *GetAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableResponse) GetAvailable() *resource.Info {
	if x != nil {
		return x.Available
	}
	return nil
}

var File_provider_provider_proto protoreflect.FileDescriptor

const file_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x17provider/provider.proto\x12\bprovider\x1a\x0eresource.proto\"2\n" +
	"\x0fAssignIDRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"B\n" +
	"\x10AssignIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12GetCapacityRequest\"E\n" +
	"\x13GetCapacityResponse\x12.\n" +
	"\bcapacity\x18\x01 \x01(\v2\x12.resource.CapacityR\bcapacity\"\x15\n" +
	"\x13GetAvailableRequest\"D\n" +
	"\x14GetAvailableResponse\x12,\n" +
	"\tavailable\x18\x01 \x01(\v2\x0e.resource.InfoR\tavailable2\xef\x01\n" +
	"\x0fProviderService\x12A\n" +
	"\bAssignID\x12\x19.provider.AssignIDRequest\x1a\x1a.provider.AssignIDResponse\x12J\n" +
	"\vGetCapacity\x12\x1c.provider.GetCapacityRequest\x1a\x1d.provider.GetCapacityResponse\x12M\n" +
	"\fGetAvailable\x12\x1d.provider.GetAvailableRequest\x1a\x1e.provider.GetAvailableResponseB<Z:github.com/9triver/iarnet/internal/proto/resource/providerb\x06proto3"

var (
	file_provider_provider_proto_rawDescOnce sync.Once
	file_provider_provider_proto_rawDescData []byte
)

func file_provider_provider_proto_rawDescGZIP() []byte {
	file_provider_provider_proto_rawDescOnce.Do(func() {
		file_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_provider_proto_rawDesc), len(file_provider_provider_proto_rawDesc)))
	})
	return file_provider_provider_proto_rawDescData
}

var file_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_provider_provider_proto_goTypes = []any{
	(*AssignIDRequest)(nil),      // 0: provider.AssignIDRequest
	(*AssignIDResponse)(nil),     // 1: provider.AssignIDResponse
	(*GetCapacityRequest)(nil),   // 2: provider.GetCapacityRequest
	(*GetCapacityResponse)(nil),  // 3: provider.GetCapacityResponse
	(*GetAvailableRequest)(nil),  // 4: provider.GetAvailableRequest
	(*GetAvailableResponse)(nil), // 5: provider.GetAvailableResponse
	(*resource.Capacity)(nil),    // 6: resource.Capacity
	(*resource.Info)(nil),        // 7: resource.Info
}
var file_provider_provider_proto_depIdxs = []int32{
	6, // 0: provider.GetCapacityResponse.capacity:type_name -> resource.Capacity
	7, // 1: provider.GetAvailableResponse.available:type_name -> resource.Info
	0, // 2: provider.ProviderService.AssignID:input_type -> provider.AssignIDRequest
	2, // 3: provider.ProviderService.GetCapacity:input_type -> provider.GetCapacityRequest
	4, // 4: provider.ProviderService.GetAvailable:input_type -> provider.GetAvailableRequest
	1, // 5: provider.ProviderService.AssignID:output_type -> provider.AssignIDResponse
	3, // 6: provider.ProviderService.GetCapacity:output_type -> provider.GetCapacityResponse
	5, // 7: provider.ProviderService.GetAvailable:output_type -> provider.GetAvailableResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_provider_provider_proto_init() }
func file_provider_provider_proto_init() {
	if File_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_provider_proto_rawDesc), len(file_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_provider_proto_goTypes,
		DependencyIndexes: file_provider_provider_proto_depIdxs,
		MessageInfos:      file_provider_provider_proto_msgTypes,
	}.Build()
	File_provider_provider_proto = out.File
	file_provider_provider_proto_goTypes = nil
	file_provider_provider_proto_depIdxs = nil
}
