// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: logger/logger.proto

package logger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoggerService_SubmitLog_FullMethodName      = "/logger.LoggerService/SubmitLog"
	LoggerService_SubmitLogBatch_FullMethodName = "/logger.LoggerService/SubmitLogBatch"
	LoggerService_StreamLogs_FullMethodName     = "/logger.LoggerService/StreamLogs"
)

// LoggerServiceClient is the client API for LoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggerServiceClient interface {
	SubmitLog(ctx context.Context, in *SubmitLogRequest, opts ...grpc.CallOption) (*SubmitLogResponse, error)
	SubmitLogBatch(ctx context.Context, in *BatchSubmitLogRequest, opts ...grpc.CallOption) (*BatchSubmitLogResponse, error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamMessage, LogStreamResponse], error)
}

type loggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerServiceClient(cc grpc.ClientConnInterface) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) SubmitLog(ctx context.Context, in *SubmitLogRequest, opts ...grpc.CallOption) (*SubmitLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLogResponse)
	err := c.cc.Invoke(ctx, LoggerService_SubmitLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerServiceClient) SubmitLogBatch(ctx context.Context, in *BatchSubmitLogRequest, opts ...grpc.CallOption) (*BatchSubmitLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSubmitLogResponse)
	err := c.cc.Invoke(ctx, LoggerService_SubmitLogBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamMessage, LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoggerService_ServiceDesc.Streams[0], LoggerService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogStreamMessage, LogStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggerService_StreamLogsClient = grpc.BidiStreamingClient[LogStreamMessage, LogStreamResponse]

// LoggerServiceServer is the server API for LoggerService service.
// All implementations must embed UnimplementedLoggerServiceServer
// for forward compatibility.
type LoggerServiceServer interface {
	SubmitLog(context.Context, *SubmitLogRequest) (*SubmitLogResponse, error)
	SubmitLogBatch(context.Context, *BatchSubmitLogRequest) (*BatchSubmitLogResponse, error)
	StreamLogs(grpc.BidiStreamingServer[LogStreamMessage, LogStreamResponse]) error
	mustEmbedUnimplementedLoggerServiceServer()
}

// UnimplementedLoggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoggerServiceServer struct{}

func (UnimplementedLoggerServiceServer) SubmitLog(context.Context, *SubmitLogRequest) (*SubmitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLog not implemented")
}
func (UnimplementedLoggerServiceServer) SubmitLogBatch(context.Context, *BatchSubmitLogRequest) (*BatchSubmitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLogBatch not implemented")
}
func (UnimplementedLoggerServiceServer) StreamLogs(grpc.BidiStreamingServer[LogStreamMessage, LogStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLoggerServiceServer) mustEmbedUnimplementedLoggerServiceServer() {}
func (UnimplementedLoggerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLoggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggerServiceServer will
// result in compilation errors.
type UnsafeLoggerServiceServer interface {
	mustEmbedUnimplementedLoggerServiceServer()
}

func RegisterLoggerServiceServer(s grpc.ServiceRegistrar, srv LoggerServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoggerService_ServiceDesc, srv)
}

func _LoggerService_SubmitLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).SubmitLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggerService_SubmitLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).SubmitLog(ctx, req.(*SubmitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggerService_SubmitLogBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSubmitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).SubmitLogBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggerService_SubmitLogBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).SubmitLogBatch(ctx, req.(*BatchSubmitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggerService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoggerServiceServer).StreamLogs(&grpc.GenericServerStream[LogStreamMessage, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggerService_StreamLogsServer = grpc.BidiStreamingServer[LogStreamMessage, LogStreamResponse]

// LoggerService_ServiceDesc is the grpc.ServiceDesc for LoggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logger.LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitLog",
			Handler:    _LoggerService_SubmitLog_Handler,
		},
		{
			MethodName: "SubmitLogBatch",
			Handler:    _LoggerService_SubmitLogBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LoggerService_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "logger/logger.proto",
}
