// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: actor/actor.proto

package actor

import (
	common "github.com/9triver/iarnet/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor 消息类型
// Actor 是执行单元，负责接收消息、执行函数、返回响应
type MessageType int32

const (
	MessageType_UNSPECIFIED     MessageType = 0 // 未知消息类型
	MessageType_ACK             MessageType = 1 // 确认消息
	MessageType_READY           MessageType = 2 // Actor 就绪，可以接收消息
	MessageType_FUNCTION        MessageType = 3 // 函数定义消息，用于注册 Actor 要执行的函数
	MessageType_INVOKE_REQUEST  MessageType = 4 // 调用请求消息，包含函数参数
	MessageType_INVOKE_RESPONSE MessageType = 5 // 调用响应消息，包含执行结果
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ACK",
		2: "READY",
		3: "FUNCTION",
		4: "INVOKE_REQUEST",
		5: "INVOKE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNSPECIFIED":     0,
		"ACK":             1,
		"READY":           2,
		"FUNCTION":        3,
		"INVOKE_REQUEST":  4,
		"INVOKE_RESPONSE": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_actor_actor_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_actor_actor_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{0}
}

// Function 消息：定义 Actor 要执行的函数
type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                               // 函数名称
	Params        []string               `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`                           // 函数参数列表
	Requirements  []string               `protobuf:"bytes,3,rep,name=Requirements,proto3" json:"Requirements,omitempty"`               // 函数依赖（Python 包）
	PickledObject []byte                 `protobuf:"bytes,4,opt,name=PickledObject,proto3" json:"PickledObject,omitempty"`             // 序列化的函数实现
	Language      common.Language        `protobuf:"varint,5,opt,name=Language,proto3,enum=common.Language" json:"Language,omitempty"` // 函数返回值的语言类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Function) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Function) GetPickledObject() []byte {
	if x != nil {
		return x.PickledObject
	}
	return nil
}

func (x *Function) GetLanguage() common.Language {
	if x != nil {
		return x.Language
	}
	return common.Language(0)
}

// InvokeArg 是调用参数
type InvokeArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=Param,proto3" json:"Param,omitempty"` // 参数名称
	Value         *common.ObjectRef      `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"` // 参数值（对象引用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeArg) Reset() {
	*x = InvokeArg{}
	mi := &file_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeArg) ProtoMessage() {}

func (x *InvokeArg) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeArg.ProtoReflect.Descriptor instead.
func (*InvokeArg) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeArg) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *InvokeArg) GetValue() *common.ObjectRef {
	if x != nil {
		return x.Value
	}
	return nil
}

// InvokeRequest 是 Actor 调用请求
// 包含会话 ID 和所有参数
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeID     string                 `protobuf:"bytes,1,opt,name=RuntimeID,proto3" json:"RuntimeID,omitempty"` // Runtime ID
	Args          []*InvokeArg           `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`           // 参数列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_actor_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetRuntimeID() string {
	if x != nil {
		return x.RuntimeID
	}
	return ""
}

func (x *InvokeRequest) GetArgs() []*InvokeArg {
	if x != nil {
		return x.Args
	}
	return nil
}

// ActorInfo 包含 Actor 的延迟信息
// 用于负载均衡和调度决策
type ActorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CalcLatency   int64                  `protobuf:"varint,2,opt,name=CalcLatency,proto3" json:"CalcLatency,omitempty"` // 计算延迟（毫秒）：函数执行时间
	LinkLatency   int64                  `protobuf:"varint,3,opt,name=LinkLatency,proto3" json:"LinkLatency,omitempty"` // 链路延迟（毫秒）：网络通信时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorInfo) Reset() {
	*x = ActorInfo{}
	mi := &file_actor_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorInfo) ProtoMessage() {}

func (x *ActorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorInfo.ProtoReflect.Descriptor instead.
func (*ActorInfo) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{3}
}

func (x *ActorInfo) GetCalcLatency() int64 {
	if x != nil {
		return x.CalcLatency
	}
	return 0
}

func (x *ActorInfo) GetLinkLatency() int64 {
	if x != nil {
		return x.LinkLatency
	}
	return 0
}

// InvokeResponse 是 Actor 调用响应
// Actor 执行函数后返回的结果
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeID     string                 `protobuf:"bytes,1,opt,name=RuntimeID,proto3" json:"RuntimeID,omitempty"` // Runtime ID
	Result        *common.ObjectRef      `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`       // 执行结果（对象引用）
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`         // 错误信息（如果有）
	Info          *ActorInfo             `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`           // Actor 延迟信息（用于负载均衡）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_actor_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeResponse) GetRuntimeID() string {
	if x != nil {
		return x.RuntimeID
	}
	return ""
}

func (x *InvokeResponse) GetResult() *common.ObjectRef {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InvokeResponse) GetInfo() *ActorInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Message 是 Actor 通信的消息封装
// Actor 通过 ZMQ 接收和发送这些消息
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=Type,proto3,enum=actor.MessageType" json:"Type,omitempty"` // 消息类型
	// Types that are valid to be assigned to Message:
	//
	//	*Message_Ack
	//	*Message_Ready
	//	*Message_Function
	//	*Message_InvokeRequest
	//	*Message_InvokeResponse
	Message       isMessage_Message `protobuf_oneof:"Message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_actor_actor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNSPECIFIED
}

func (x *Message) GetMessage() isMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetAck() *common.Ack {
	if x != nil {
		if x, ok := x.Message.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetReady() *common.Ready {
	if x != nil {
		if x, ok := x.Message.(*Message_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Message) GetFunction() *Function {
	if x != nil {
		if x, ok := x.Message.(*Message_Function); ok {
			return x.Function
		}
	}
	return nil
}

func (x *Message) GetInvokeRequest() *InvokeRequest {
	if x != nil {
		if x, ok := x.Message.(*Message_InvokeRequest); ok {
			return x.InvokeRequest
		}
	}
	return nil
}

func (x *Message) GetInvokeResponse() *InvokeResponse {
	if x != nil {
		if x, ok := x.Message.(*Message_InvokeResponse); ok {
			return x.InvokeResponse
		}
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_Ack struct {
	Ack *common.Ack `protobuf:"bytes,2,opt,name=Ack,proto3,oneof"` // 确认消息
}

type Message_Ready struct {
	Ready *common.Ready `protobuf:"bytes,3,opt,name=Ready,proto3,oneof"` // 就绪消息
}

type Message_Function struct {
	Function *Function `protobuf:"bytes,4,opt,name=Function,proto3,oneof"` // 函数定义消息
}

type Message_InvokeRequest struct {
	InvokeRequest *InvokeRequest `protobuf:"bytes,5,opt,name=InvokeRequest,proto3,oneof"` // 调用请求消息
}

type Message_InvokeResponse struct {
	InvokeResponse *InvokeResponse `protobuf:"bytes,6,opt,name=InvokeResponse,proto3,oneof"` // 调用响应消息
}

func (*Message_Ack) isMessage_Message() {}

func (*Message_Ready) isMessage_Message() {}

func (*Message_Function) isMessage_Message() {}

func (*Message_InvokeRequest) isMessage_Message() {}

func (*Message_InvokeResponse) isMessage_Message() {}

var File_actor_actor_proto protoreflect.FileDescriptor

const file_actor_actor_proto_rawDesc = "" +
	"\n" +
	"\x11actor/actor.proto\x12\x05actor\x1a\x12common/types.proto\x1a\x15common/messages.proto\"\xae\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x03(\tR\x06Params\x12\"\n" +
	"\fRequirements\x18\x03 \x03(\tR\fRequirements\x12$\n" +
	"\rPickledObject\x18\x04 \x01(\fR\rPickledObject\x12,\n" +
	"\bLanguage\x18\x05 \x01(\x0e2\x10.common.LanguageR\bLanguage\"J\n" +
	"\tInvokeArg\x12\x14\n" +
	"\x05Param\x18\x01 \x01(\tR\x05Param\x12'\n" +
	"\x05Value\x18\x02 \x01(\v2\x11.common.ObjectRefR\x05Value\"S\n" +
	"\rInvokeRequest\x12\x1c\n" +
	"\tRuntimeID\x18\x01 \x01(\tR\tRuntimeID\x12$\n" +
	"\x04Args\x18\x02 \x03(\v2\x10.actor.InvokeArgR\x04Args\"O\n" +
	"\tActorInfo\x12 \n" +
	"\vCalcLatency\x18\x02 \x01(\x03R\vCalcLatency\x12 \n" +
	"\vLinkLatency\x18\x03 \x01(\x03R\vLinkLatency\"\x95\x01\n" +
	"\x0eInvokeResponse\x12\x1c\n" +
	"\tRuntimeID\x18\x01 \x01(\tR\tRuntimeID\x12)\n" +
	"\x06Result\x18\x02 \x01(\v2\x11.common.ObjectRefR\x06Result\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\x12$\n" +
	"\x04Info\x18\x04 \x01(\v2\x10.actor.ActorInfoR\x04Info\"\xb2\x02\n" +
	"\aMessage\x12&\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x12.actor.MessageTypeR\x04Type\x12\x1f\n" +
	"\x03Ack\x18\x02 \x01(\v2\v.common.AckH\x00R\x03Ack\x12%\n" +
	"\x05Ready\x18\x03 \x01(\v2\r.common.ReadyH\x00R\x05Ready\x12-\n" +
	"\bFunction\x18\x04 \x01(\v2\x0f.actor.FunctionH\x00R\bFunction\x12<\n" +
	"\rInvokeRequest\x18\x05 \x01(\v2\x14.actor.InvokeRequestH\x00R\rInvokeRequest\x12?\n" +
	"\x0eInvokeResponse\x18\x06 \x01(\v2\x15.actor.InvokeResponseH\x00R\x0eInvokeResponseB\t\n" +
	"\aMessage*i\n" +
	"\vMessageType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ACK\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\f\n" +
	"\bFUNCTION\x10\x03\x12\x12\n" +
	"\x0eINVOKE_REQUEST\x10\x04\x12\x13\n" +
	"\x0fINVOKE_RESPONSE\x10\x05B6Z4github.com/9triver/iarnet/internal/proto/ignis/actorb\x06proto3"

var (
	file_actor_actor_proto_rawDescOnce sync.Once
	file_actor_actor_proto_rawDescData []byte
)

func file_actor_actor_proto_rawDescGZIP() []byte {
	file_actor_actor_proto_rawDescOnce.Do(func() {
		file_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_actor_proto_rawDesc), len(file_actor_actor_proto_rawDesc)))
	})
	return file_actor_actor_proto_rawDescData
}

var file_actor_actor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_actor_actor_proto_goTypes = []any{
	(MessageType)(0),         // 0: actor.MessageType
	(*Function)(nil),         // 1: actor.Function
	(*InvokeArg)(nil),        // 2: actor.InvokeArg
	(*InvokeRequest)(nil),    // 3: actor.InvokeRequest
	(*ActorInfo)(nil),        // 4: actor.ActorInfo
	(*InvokeResponse)(nil),   // 5: actor.InvokeResponse
	(*Message)(nil),          // 6: actor.Message
	(common.Language)(0),     // 7: common.Language
	(*common.ObjectRef)(nil), // 8: common.ObjectRef
	(*common.Ack)(nil),       // 9: common.Ack
	(*common.Ready)(nil),     // 10: common.Ready
}
var file_actor_actor_proto_depIdxs = []int32{
	7,  // 0: actor.Function.Language:type_name -> common.Language
	8,  // 1: actor.InvokeArg.Value:type_name -> common.ObjectRef
	2,  // 2: actor.InvokeRequest.Args:type_name -> actor.InvokeArg
	8,  // 3: actor.InvokeResponse.Result:type_name -> common.ObjectRef
	4,  // 4: actor.InvokeResponse.Info:type_name -> actor.ActorInfo
	0,  // 5: actor.Message.Type:type_name -> actor.MessageType
	9,  // 6: actor.Message.Ack:type_name -> common.Ack
	10, // 7: actor.Message.Ready:type_name -> common.Ready
	1,  // 8: actor.Message.Function:type_name -> actor.Function
	3,  // 9: actor.Message.InvokeRequest:type_name -> actor.InvokeRequest
	5,  // 10: actor.Message.InvokeResponse:type_name -> actor.InvokeResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_actor_actor_proto_init() }
func file_actor_actor_proto_init() {
	if File_actor_actor_proto != nil {
		return
	}
	file_actor_actor_proto_msgTypes[5].OneofWrappers = []any{
		(*Message_Ack)(nil),
		(*Message_Ready)(nil),
		(*Message_Function)(nil),
		(*Message_InvokeRequest)(nil),
		(*Message_InvokeResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_actor_proto_rawDesc), len(file_actor_actor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_actor_proto_goTypes,
		DependencyIndexes: file_actor_actor_proto_depIdxs,
		EnumInfos:         file_actor_actor_proto_enumTypes,
		MessageInfos:      file_actor_actor_proto_msgTypes,
	}.Build()
	File_actor_actor_proto = out.File
	file_actor_actor_proto_goTypes = nil
	file_actor_actor_proto_depIdxs = nil
}
