// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: resource/component/component.proto

package component

import (
	common "github.com/9triver/iarnet/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNSPECIFIED MessageType = 0
	MessageType_READY       MessageType = 1
	MessageType_PAYLOAD     MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "READY",
		2: "PAYLOAD",
	}
	MessageType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"READY":       1,
		"PAYLOAD":     2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_component_component_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_resource_component_component_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_resource_component_component_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=Type,proto3,enum=resource.component.MessageType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Message_Ready
	//	*Message_Payload
	Message       isMessage_Message `protobuf_oneof:"Message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_resource_component_component_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_resource_component_component_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_resource_component_component_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNSPECIFIED
}

func (x *Message) GetMessage() isMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetReady() *common.Ready {
	if x != nil {
		if x, ok := x.Message.(*Message_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Message) GetPayload() *anypb.Any {
	if x != nil {
		if x, ok := x.Message.(*Message_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_Ready struct {
	Ready *common.Ready `protobuf:"bytes,2,opt,name=Ready,proto3,oneof"`
}

type Message_Payload struct {
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=Payload,proto3,oneof"` // Any protobuf message (corresponds to proto.Message in Go)
}

func (*Message_Ready) isMessage_Message() {}

func (*Message_Payload) isMessage_Message() {}

var File_resource_component_component_proto protoreflect.FileDescriptor

const file_resource_component_component_proto_rawDesc = "" +
	"\n" +
	"\"resource/component/component.proto\x12\x12resource.component\x1a\x15common/messages.proto\x1a\x19google/protobuf/any.proto\"\xa2\x01\n" +
	"\aMessage\x123\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1f.resource.component.MessageTypeR\x04Type\x12%\n" +
	"\x05Ready\x18\x02 \x01(\v2\r.common.ReadyH\x00R\x05Ready\x120\n" +
	"\aPayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\aPayloadB\t\n" +
	"\aMessage*6\n" +
	"\vMessageType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\v\n" +
	"\aPAYLOAD\x10\x02B=Z;github.com/9triver/iarnet/internal/proto/resource/componentb\x06proto3"

var (
	file_resource_component_component_proto_rawDescOnce sync.Once
	file_resource_component_component_proto_rawDescData []byte
)

func file_resource_component_component_proto_rawDescGZIP() []byte {
	file_resource_component_component_proto_rawDescOnce.Do(func() {
		file_resource_component_component_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_component_component_proto_rawDesc), len(file_resource_component_component_proto_rawDesc)))
	})
	return file_resource_component_component_proto_rawDescData
}

var file_resource_component_component_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_component_component_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resource_component_component_proto_goTypes = []any{
	(MessageType)(0),     // 0: resource.component.MessageType
	(*Message)(nil),      // 1: resource.component.Message
	(*common.Ready)(nil), // 2: common.Ready
	(*anypb.Any)(nil),    // 3: google.protobuf.Any
}
var file_resource_component_component_proto_depIdxs = []int32{
	0, // 0: resource.component.Message.Type:type_name -> resource.component.MessageType
	2, // 1: resource.component.Message.Ready:type_name -> common.Ready
	3, // 2: resource.component.Message.Payload:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_component_component_proto_init() }
func file_resource_component_component_proto_init() {
	if File_resource_component_component_proto != nil {
		return
	}
	file_resource_component_component_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Ready)(nil),
		(*Message_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_component_component_proto_rawDesc), len(file_resource_component_component_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_component_component_proto_goTypes,
		DependencyIndexes: file_resource_component_component_proto_depIdxs,
		EnumInfos:         file_resource_component_component_proto_enumTypes,
		MessageInfos:      file_resource_component_component_proto_msgTypes,
	}.Build()
	File_resource_component_component_proto = out.File
	file_resource_component_component_proto_goTypes = nil
	file_resource_component_component_proto_depIdxs = nil
}
