# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/scheduler/scheduler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resource/scheduler/scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from resource import resource_pb2 as resource_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"resource/scheduler/scheduler.proto\x12\tscheduler\x1a\x17resource/resource.proto\"\x8c\x01\n\x16\x44\x65ployComponentRequest\x12\x13\n\x0bruntime_env\x18\x01 \x01(\t\x12(\n\x10resource_request\x18\x02 \x01(\x0b\x32\x0e.resource.Info\x12\x16\n\x0etarget_node_id\x18\x03 \x01(\t\x12\x1b\n\x13target_node_address\x18\x04 \x01(\t\"\x9f\x01\n\x17\x44\x65ployComponentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12+\n\tcomponent\x18\x03 \x01(\x0b\x32\x18.scheduler.ComponentInfo\x12\x0f\n\x07node_id\x18\x04 \x01(\t\x12\x11\n\tnode_name\x18\x05 \x01(\t\x12\x13\n\x0bprovider_id\x18\x06 \x01(\t\"q\n\rComponentInfo\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12&\n\x0eresource_usage\x18\x03 \x01(\x0b\x32\x0e.resource.Info\x12\x13\n\x0bprovider_id\x18\x04 \x01(\t\"C\n\x1aGetDeploymentStatusRequest\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\"\x96\x01\n\x1bGetDeploymentStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12*\n\x06status\x18\x03 \x01(\x0e\x32\x1a.scheduler.ComponentStatus\x12+\n\tcomponent\x18\x04 \x01(\x0b\x32\x18.scheduler.ComponentInfo*\xa7\x01\n\x0f\x43omponentStatus\x12\x1c\n\x18\x43OMPONENT_STATUS_UNKNOWN\x10\x00\x12\x1e\n\x1a\x43OMPONENT_STATUS_DEPLOYING\x10\x01\x12\x1c\n\x18\x43OMPONENT_STATUS_RUNNING\x10\x02\x12\x1c\n\x18\x43OMPONENT_STATUS_STOPPED\x10\x03\x12\x1a\n\x16\x43OMPONENT_STATUS_ERROR\x10\x04\x32\xd2\x01\n\x10SchedulerService\x12X\n\x0f\x44\x65ployComponent\x12!.scheduler.DeployComponentRequest\x1a\".scheduler.DeployComponentResponse\x12\x64\n\x13GetDeploymentStatus\x12%.scheduler.GetDeploymentStatusRequest\x1a&.scheduler.GetDeploymentStatusResponseB=Z;github.com/9triver/iarnet/internal/proto/resource/schedulerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.scheduler.scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/9triver/iarnet/internal/proto/resource/scheduler'
  _globals['_COMPONENTSTATUS']._serialized_start=717
  _globals['_COMPONENTSTATUS']._serialized_end=884
  _globals['_DEPLOYCOMPONENTREQUEST']._serialized_start=75
  _globals['_DEPLOYCOMPONENTREQUEST']._serialized_end=215
  _globals['_DEPLOYCOMPONENTRESPONSE']._serialized_start=218
  _globals['_DEPLOYCOMPONENTRESPONSE']._serialized_end=377
  _globals['_COMPONENTINFO']._serialized_start=379
  _globals['_COMPONENTINFO']._serialized_end=492
  _globals['_GETDEPLOYMENTSTATUSREQUEST']._serialized_start=494
  _globals['_GETDEPLOYMENTSTATUSREQUEST']._serialized_end=561
  _globals['_GETDEPLOYMENTSTATUSRESPONSE']._serialized_start=564
  _globals['_GETDEPLOYMENTSTATUSRESPONSE']._serialized_end=714
  _globals['_SCHEDULERSERVICE']._serialized_start=887
  _globals['_SCHEDULERSERVICE']._serialized_end=1097
# @@protoc_insertion_point(module_scope)
