// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/ignis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeAnalysisService_AnalyzeCode_FullMethodName = "/ignis.CodeAnalysisService/AnalyzeCode"
)

// CodeAnalysisServiceClient is the client API for CodeAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Code Analysis Service for Ignis Platform
type CodeAnalysisServiceClient interface {
	AnalyzeCode(ctx context.Context, in *CodeAnalysisRequest, opts ...grpc.CallOption) (*CodeAnalysisResponse, error)
}

type codeAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeAnalysisServiceClient(cc grpc.ClientConnInterface) CodeAnalysisServiceClient {
	return &codeAnalysisServiceClient{cc}
}

func (c *codeAnalysisServiceClient) AnalyzeCode(ctx context.Context, in *CodeAnalysisRequest, opts ...grpc.CallOption) (*CodeAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeAnalysisResponse)
	err := c.cc.Invoke(ctx, CodeAnalysisService_AnalyzeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeAnalysisServiceServer is the server API for CodeAnalysisService service.
// All implementations must embed UnimplementedCodeAnalysisServiceServer
// for forward compatibility.
//
// Code Analysis Service for Ignis Platform
type CodeAnalysisServiceServer interface {
	AnalyzeCode(context.Context, *CodeAnalysisRequest) (*CodeAnalysisResponse, error)
	mustEmbedUnimplementedCodeAnalysisServiceServer()
}

// UnimplementedCodeAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeAnalysisServiceServer struct{}

func (UnimplementedCodeAnalysisServiceServer) AnalyzeCode(context.Context, *CodeAnalysisRequest) (*CodeAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeCode not implemented")
}
func (UnimplementedCodeAnalysisServiceServer) mustEmbedUnimplementedCodeAnalysisServiceServer() {}
func (UnimplementedCodeAnalysisServiceServer) testEmbeddedByValue()                             {}

// UnsafeCodeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeAnalysisServiceServer will
// result in compilation errors.
type UnsafeCodeAnalysisServiceServer interface {
	mustEmbedUnimplementedCodeAnalysisServiceServer()
}

func RegisterCodeAnalysisServiceServer(s grpc.ServiceRegistrar, srv CodeAnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedCodeAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeAnalysisService_ServiceDesc, srv)
}

func _CodeAnalysisService_AnalyzeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeAnalysisServiceServer).AnalyzeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeAnalysisService_AnalyzeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeAnalysisServiceServer).AnalyzeCode(ctx, req.(*CodeAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeAnalysisService_ServiceDesc is the grpc.ServiceDesc for CodeAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ignis.CodeAnalysisService",
	HandlerType: (*CodeAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeCode",
			Handler:    _CodeAnalysisService_AnalyzeCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ignis.proto",
}
