// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/ignis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider information for analysis
type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	PeerAddress   string                 `protobuf:"bytes,7,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"` // Which peer manages this provider
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_proto_ignis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProviderInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProviderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProviderInfo) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

// Code Analysis Messages
type CodeAnalysisRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId      string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CodeContent        string                 `protobuf:"bytes,2,opt,name=code_content,json=codeContent,proto3" json:"code_content,omitempty"` // Base64 encoded code archive
	AvailableProviders []*ProviderInfo        `protobuf:"bytes,3,rep,name=available_providers,json=availableProviders,proto3" json:"available_providers,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata like language, framework
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CodeAnalysisRequest) Reset() {
	*x = CodeAnalysisRequest{}
	mi := &file_proto_ignis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAnalysisRequest) ProtoMessage() {}

func (x *CodeAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAnalysisRequest.ProtoReflect.Descriptor instead.
func (*CodeAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{1}
}

func (x *CodeAnalysisRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CodeAnalysisRequest) GetCodeContent() string {
	if x != nil {
		return x.CodeContent
	}
	return ""
}

func (x *CodeAnalysisRequest) GetAvailableProviders() []*ProviderInfo {
	if x != nil {
		return x.AvailableProviders
	}
	return nil
}

func (x *CodeAnalysisRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Component struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                 // "web", "api", "worker", "database", "cache"
	Image            string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`               // Docker image or build instructions
	Dependencies     []string               `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"` // Component IDs this depends on
	Ports            []int32                `protobuf:"varint,6,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources        *ResourceRequirements  `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	ProviderType     string                 `protobuf:"bytes,9,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`              // Preferred provider type
	ProviderId       string                 `protobuf:"bytes,10,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                   // Specific provider ID if required
	DeploymentConfig []byte                 `protobuf:"bytes,11,opt,name=deployment_config,json=deploymentConfig,proto3" json:"deployment_config,omitempty"` // Serialized deployment configuration
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_proto_ignis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{2}
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Component) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Component) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Component) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *Component) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Component) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *Component) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Component) GetDeploymentConfig() []byte {
	if x != nil {
		return x.DeploymentConfig
	}
	return nil
}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        float64                `protobuf:"fixed64,2,opt,name=memory,proto3" json:"memory,omitempty"` // In GB
	Gpu           float64                `protobuf:"fixed64,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Storage       float64                `protobuf:"fixed64,4,opt,name=storage,proto3" json:"storage,omitempty"` // In GB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_proto_ignis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceRequirements) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceRequirements) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ResourceRequirements) GetGpu() float64 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

func (x *ResourceRequirements) GetStorage() float64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

type DAGEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromComponent    string                 `protobuf:"bytes,1,opt,name=from_component,json=fromComponent,proto3" json:"from_component,omitempty"`
	ToComponent      string                 `protobuf:"bytes,2,opt,name=to_component,json=toComponent,proto3" json:"to_component,omitempty"`
	ConnectionType   string                 `protobuf:"bytes,3,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"` // "http", "grpc", "database", "message_queue"
	ConnectionConfig map[string]string      `protobuf:"bytes,4,rep,name=connection_config,json=connectionConfig,proto3" json:"connection_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DAGEdge) Reset() {
	*x = DAGEdge{}
	mi := &file_proto_ignis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGEdge) ProtoMessage() {}

func (x *DAGEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGEdge.ProtoReflect.Descriptor instead.
func (*DAGEdge) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{4}
}

func (x *DAGEdge) GetFromComponent() string {
	if x != nil {
		return x.FromComponent
	}
	return ""
}

func (x *DAGEdge) GetToComponent() string {
	if x != nil {
		return x.ToComponent
	}
	return ""
}

func (x *DAGEdge) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *DAGEdge) GetConnectionConfig() map[string]string {
	if x != nil {
		return x.ConnectionConfig
	}
	return nil
}

type CodeAnalysisResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Components       []*Component           `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	Edges            []*DAGEdge             `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	GlobalConfig     map[string]string      `protobuf:"bytes,5,rep,name=global_config,json=globalConfig,proto3" json:"global_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Global configuration like secrets, env vars
	AnalysisMetadata string                 `protobuf:"bytes,6,opt,name=analysis_metadata,json=analysisMetadata,proto3" json:"analysis_metadata,omitempty"`                                                               // JSON metadata about the analysis
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CodeAnalysisResponse) Reset() {
	*x = CodeAnalysisResponse{}
	mi := &file_proto_ignis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAnalysisResponse) ProtoMessage() {}

func (x *CodeAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ignis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAnalysisResponse.ProtoReflect.Descriptor instead.
func (*CodeAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_ignis_proto_rawDescGZIP(), []int{5}
}

func (x *CodeAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CodeAnalysisResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CodeAnalysisResponse) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *CodeAnalysisResponse) GetEdges() []*DAGEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *CodeAnalysisResponse) GetGlobalConfig() map[string]string {
	if x != nil {
		return x.GlobalConfig
	}
	return nil
}

func (x *CodeAnalysisResponse) GetAnalysisMetadata() string {
	if x != nil {
		return x.AnalysisMetadata
	}
	return ""
}

var File_proto_ignis_proto protoreflect.FileDescriptor

const file_proto_ignis_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ignis.proto\x12\x05ignis\"\xa9\x01\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12!\n" +
	"\fpeer_address\x18\a \x01(\tR\vpeerAddress\"\xa8\x02\n" +
	"\x13CodeAnalysisRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12!\n" +
	"\fcode_content\x18\x02 \x01(\tR\vcodeContent\x12D\n" +
	"\x13available_providers\x18\x03 \x03(\v2\x13.ignis.ProviderInfoR\x12availableProviders\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.ignis.CodeAnalysisRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x03\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\"\n" +
	"\fdependencies\x18\x05 \x03(\tR\fdependencies\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\x05R\x05ports\x12C\n" +
	"\venvironment\x18\a \x03(\v2!.ignis.Component.EnvironmentEntryR\venvironment\x129\n" +
	"\tresources\x18\b \x01(\v2\x1b.ignis.ResourceRequirementsR\tresources\x12#\n" +
	"\rprovider_type\x18\t \x01(\tR\fproviderType\x12\x1f\n" +
	"\vprovider_id\x18\n" +
	" \x01(\tR\n" +
	"providerId\x12+\n" +
	"\x11deployment_config\x18\v \x01(\fR\x10deploymentConfig\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x14ResourceRequirements\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x01R\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x01R\x03gpu\x12\x18\n" +
	"\astorage\x18\x04 \x01(\x01R\astorage\"\x94\x02\n" +
	"\aDAGEdge\x12%\n" +
	"\x0efrom_component\x18\x01 \x01(\tR\rfromComponent\x12!\n" +
	"\fto_component\x18\x02 \x01(\tR\vtoComponent\x12'\n" +
	"\x0fconnection_type\x18\x03 \x01(\tR\x0econnectionType\x12Q\n" +
	"\x11connection_config\x18\x04 \x03(\v2$.ignis.DAGEdge.ConnectionConfigEntryR\x10connectionConfig\x1aC\n" +
	"\x15ConnectionConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x02\n" +
	"\x14CodeAnalysisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x10.ignis.ComponentR\n" +
	"components\x12$\n" +
	"\x05edges\x18\x04 \x03(\v2\x0e.ignis.DAGEdgeR\x05edges\x12R\n" +
	"\rglobal_config\x18\x05 \x03(\v2-.ignis.CodeAnalysisResponse.GlobalConfigEntryR\fglobalConfig\x12+\n" +
	"\x11analysis_metadata\x18\x06 \x01(\tR\x10analysisMetadata\x1a?\n" +
	"\x11GlobalConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012]\n" +
	"\x13CodeAnalysisService\x12F\n" +
	"\vAnalyzeCode\x12\x1a.ignis.CodeAnalysisRequest\x1a\x1b.ignis.CodeAnalysisResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_ignis_proto_rawDescOnce sync.Once
	file_proto_ignis_proto_rawDescData []byte
)

func file_proto_ignis_proto_rawDescGZIP() []byte {
	file_proto_ignis_proto_rawDescOnce.Do(func() {
		file_proto_ignis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ignis_proto_rawDesc), len(file_proto_ignis_proto_rawDesc)))
	})
	return file_proto_ignis_proto_rawDescData
}

var file_proto_ignis_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ignis_proto_goTypes = []any{
	(*ProviderInfo)(nil),         // 0: ignis.ProviderInfo
	(*CodeAnalysisRequest)(nil),  // 1: ignis.CodeAnalysisRequest
	(*Component)(nil),            // 2: ignis.Component
	(*ResourceRequirements)(nil), // 3: ignis.ResourceRequirements
	(*DAGEdge)(nil),              // 4: ignis.DAGEdge
	(*CodeAnalysisResponse)(nil), // 5: ignis.CodeAnalysisResponse
	nil,                          // 6: ignis.CodeAnalysisRequest.MetadataEntry
	nil,                          // 7: ignis.Component.EnvironmentEntry
	nil,                          // 8: ignis.DAGEdge.ConnectionConfigEntry
	nil,                          // 9: ignis.CodeAnalysisResponse.GlobalConfigEntry
}
var file_proto_ignis_proto_depIdxs = []int32{
	0, // 0: ignis.CodeAnalysisRequest.available_providers:type_name -> ignis.ProviderInfo
	6, // 1: ignis.CodeAnalysisRequest.metadata:type_name -> ignis.CodeAnalysisRequest.MetadataEntry
	7, // 2: ignis.Component.environment:type_name -> ignis.Component.EnvironmentEntry
	3, // 3: ignis.Component.resources:type_name -> ignis.ResourceRequirements
	8, // 4: ignis.DAGEdge.connection_config:type_name -> ignis.DAGEdge.ConnectionConfigEntry
	2, // 5: ignis.CodeAnalysisResponse.components:type_name -> ignis.Component
	4, // 6: ignis.CodeAnalysisResponse.edges:type_name -> ignis.DAGEdge
	9, // 7: ignis.CodeAnalysisResponse.global_config:type_name -> ignis.CodeAnalysisResponse.GlobalConfigEntry
	1, // 8: ignis.CodeAnalysisService.AnalyzeCode:input_type -> ignis.CodeAnalysisRequest
	5, // 9: ignis.CodeAnalysisService.AnalyzeCode:output_type -> ignis.CodeAnalysisResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ignis_proto_init() }
func file_proto_ignis_proto_init() {
	if File_proto_ignis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ignis_proto_rawDesc), len(file_proto_ignis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ignis_proto_goTypes,
		DependencyIndexes: file_proto_ignis_proto_depIdxs,
		MessageInfos:      file_proto_ignis_proto_msgTypes,
	}.Build()
	File_proto_ignis_proto = out.File
	file_proto_ignis_proto_goTypes = nil
	file_proto_ignis_proto_depIdxs = nil
}
