// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/peer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownPeers    []string               `protobuf:"bytes,1,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"` // List of peer addresses (e.g., "host:port")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_proto_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetKnownPeers() []string {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownPeers    []string               `protobuf:"bytes,1,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_proto_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeResponse) GetKnownPeers() []string {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

type ProviderExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderExchangeRequest) Reset() {
	*x = ProviderExchangeRequest{}
	mi := &file_proto_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderExchangeRequest) ProtoMessage() {}

func (x *ProviderExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderExchangeRequest.ProtoReflect.Descriptor instead.
func (*ProviderExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderExchangeRequest) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderExchangeResponse) Reset() {
	*x = ProviderExchangeResponse{}
	mi := &file_proto_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderExchangeResponse) ProtoMessage() {}

func (x *ProviderExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderExchangeResponse.ProtoReflect.Descriptor instead.
func (*ProviderExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderExchangeResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Remote provider method calls
type ProviderCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Serialized method parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCallRequest) Reset() {
	*x = ProviderCallRequest{}
	mi := &file_proto_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCallRequest) ProtoMessage() {}

func (x *ProviderCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCallRequest.ProtoReflect.Descriptor instead.
func (*ProviderCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderCallRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProviderCallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProviderCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // Serialized method result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCallResponse) Reset() {
	*x = ProviderCallResponse{}
	mi := &file_proto_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCallResponse) ProtoMessage() {}

func (x *ProviderCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCallResponse.ProtoReflect.Descriptor instead.
func (*ProviderCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProviderCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProviderCallResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_peer_proto protoreflect.FileDescriptor

const file_proto_peer_proto_rawDesc = "" +
	"\n" +
	"\x10proto/peer.proto\x12\x04peer\x1a\x11proto/ignis.proto\"2\n" +
	"\x0fExchangeRequest\x12\x1f\n" +
	"\vknown_peers\x18\x01 \x03(\tR\n" +
	"knownPeers\"3\n" +
	"\x10ExchangeResponse\x12\x1f\n" +
	"\vknown_peers\x18\x01 \x03(\tR\n" +
	"knownPeers\"L\n" +
	"\x17ProviderExchangeRequest\x121\n" +
	"\tproviders\x18\x01 \x03(\v2\x13.ignis.ProviderInfoR\tproviders\"M\n" +
	"\x18ProviderExchangeResponse\x121\n" +
	"\tproviders\x18\x01 \x03(\v2\x13.ignis.ProviderInfoR\tproviders\"h\n" +
	"\x13ProviderCallRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"^\n" +
	"\x14ProviderCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result2\xe8\x01\n" +
	"\vPeerService\x12>\n" +
	"\rExchangePeers\x12\x15.peer.ExchangeRequest\x1a\x16.peer.ExchangeResponse\x12R\n" +
	"\x11ExchangeProviders\x12\x1d.peer.ProviderExchangeRequest\x1a\x1e.peer.ProviderExchangeResponse\x12E\n" +
	"\fCallProvider\x12\x19.peer.ProviderCallRequest\x1a\x1a.peer.ProviderCallResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_peer_proto_rawDescOnce sync.Once
	file_proto_peer_proto_rawDescData []byte
)

func file_proto_peer_proto_rawDescGZIP() []byte {
	file_proto_peer_proto_rawDescOnce.Do(func() {
		file_proto_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_peer_proto_rawDesc), len(file_proto_peer_proto_rawDesc)))
	})
	return file_proto_peer_proto_rawDescData
}

var file_proto_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_peer_proto_goTypes = []any{
	(*ExchangeRequest)(nil),          // 0: peer.ExchangeRequest
	(*ExchangeResponse)(nil),         // 1: peer.ExchangeResponse
	(*ProviderExchangeRequest)(nil),  // 2: peer.ProviderExchangeRequest
	(*ProviderExchangeResponse)(nil), // 3: peer.ProviderExchangeResponse
	(*ProviderCallRequest)(nil),      // 4: peer.ProviderCallRequest
	(*ProviderCallResponse)(nil),     // 5: peer.ProviderCallResponse
	(*ProviderInfo)(nil),             // 6: ignis.ProviderInfo
}
var file_proto_peer_proto_depIdxs = []int32{
	6, // 0: peer.ProviderExchangeRequest.providers:type_name -> ignis.ProviderInfo
	6, // 1: peer.ProviderExchangeResponse.providers:type_name -> ignis.ProviderInfo
	0, // 2: peer.PeerService.ExchangePeers:input_type -> peer.ExchangeRequest
	2, // 3: peer.PeerService.ExchangeProviders:input_type -> peer.ProviderExchangeRequest
	4, // 4: peer.PeerService.CallProvider:input_type -> peer.ProviderCallRequest
	1, // 5: peer.PeerService.ExchangePeers:output_type -> peer.ExchangeResponse
	3, // 6: peer.PeerService.ExchangeProviders:output_type -> peer.ProviderExchangeResponse
	5, // 7: peer.PeerService.CallProvider:output_type -> peer.ProviderCallResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_peer_proto_init() }
func file_proto_peer_proto_init() {
	if File_proto_peer_proto != nil {
		return
	}
	file_proto_ignis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_peer_proto_rawDesc), len(file_proto_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_peer_proto_goTypes,
		DependencyIndexes: file_proto_peer_proto_depIdxs,
		MessageInfos:      file_proto_peer_proto_msgTypes,
	}.Build()
	File_proto_peer_proto = out.File
	file_proto_peer_proto_goTypes = nil
	file_proto_peer_proto_depIdxs = nil
}
