# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from resource.provider import provider_pb2 as resource_dot_provider_dot_provider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resource/provider/provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/resource.provider.Service/Connect',
                request_serializer=resource_dot_provider_dot_provider__pb2.ConnectRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/resource.provider.Service/Disconnect',
                request_serializer=resource_dot_provider_dot_provider__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.GetCapacity = channel.unary_unary(
                '/resource.provider.Service/GetCapacity',
                request_serializer=resource_dot_provider_dot_provider__pb2.GetCapacityRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.GetCapacityResponse.FromString,
                _registered_method=True)
        self.GetAvailable = channel.unary_unary(
                '/resource.provider.Service/GetAvailable',
                request_serializer=resource_dot_provider_dot_provider__pb2.GetAvailableRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.GetAvailableResponse.FromString,
                _registered_method=True)
        self.Deploy = channel.unary_unary(
                '/resource.provider.Service/Deploy',
                request_serializer=resource_dot_provider_dot_provider__pb2.DeployRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/resource.provider.Service/HealthCheck',
                request_serializer=resource_dot_provider_dot_provider__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetRealTimeUsage = channel.unary_unary(
                '/resource.provider.Service/GetRealTimeUsage',
                request_serializer=resource_dot_provider_dot_provider__pb2.GetRealTimeUsageRequest.SerializeToString,
                response_deserializer=resource_dot_provider_dot_provider__pb2.GetRealTimeUsageResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deploy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.ConnectRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.DisconnectRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.DisconnectResponse.SerializeToString,
            ),
            'GetCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapacity,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.GetCapacityRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.GetCapacityResponse.SerializeToString,
            ),
            'GetAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailable,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.GetAvailableRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.GetAvailableResponse.SerializeToString,
            ),
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.DeployRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.DeployResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.HealthCheckRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetRealTimeUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeUsage,
                    request_deserializer=resource_dot_provider_dot_provider__pb2.GetRealTimeUsageRequest.FromString,
                    response_serializer=resource_dot_provider_dot_provider__pb2.GetRealTimeUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resource.provider.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resource.provider.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/Connect',
            resource_dot_provider_dot_provider__pb2.ConnectRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/Disconnect',
            resource_dot_provider_dot_provider__pb2.DisconnectRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/GetCapacity',
            resource_dot_provider_dot_provider__pb2.GetCapacityRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.GetCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/GetAvailable',
            resource_dot_provider_dot_provider__pb2.GetAvailableRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.GetAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/Deploy',
            resource_dot_provider_dot_provider__pb2.DeployRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/HealthCheck',
            resource_dot_provider_dot_provider__pb2.HealthCheckRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRealTimeUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource.provider.Service/GetRealTimeUsage',
            resource_dot_provider_dot_provider__pb2.GetRealTimeUsageRequest.SerializeToString,
            resource_dot_provider_dot_provider__pb2.GetRealTimeUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
