# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/resource.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resource/resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17resource/resource.proto\x12\x08resource\"0\n\x04Info\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x03\x12\x0e\n\x06memory\x18\x02 \x01(\x03\x12\x0b\n\x03gpu\x18\x03 \x01(\x03\"j\n\x08\x43\x61pacity\x12\x1d\n\x05total\x18\x01 \x01(\x0b\x32\x0e.resource.Info\x12\x1c\n\x04used\x18\x02 \x01(\x0b\x32\x0e.resource.Info\x12!\n\tavailable\x18\x03 \x01(\x0b\x32\x0e.resource.Info\"/\n\x0fResourceRequest\x12\x1c\n\x04info\x18\x01 \x01(\x0b\x32\x0e.resource.InfoB3Z1github.com/9triver/iarnet/internal/proto/resourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/9triver/iarnet/internal/proto/resource'
  _globals['_INFO']._serialized_start=37
  _globals['_INFO']._serialized_end=85
  _globals['_CAPACITY']._serialized_start=87
  _globals['_CAPACITY']._serialized_end=193
  _globals['_RESOURCEREQUEST']._serialized_start=195
  _globals['_RESOURCEREQUEST']._serialized_end=242
# @@protoc_insertion_point(module_scope)
