# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from global.registry import registry_pb2 as global_dot_registry_dot_registry__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in global/registry/registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """==================== 服务定义 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/global.registry.Service/RegisterNode',
                request_serializer=global_dot_registry_dot_registry__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=global_dot_registry_dot_registry__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/global.registry.Service/HealthCheck',
                request_serializer=global_dot_registry_dot_registry__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=global_dot_registry_dot_registry__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """==================== 服务定义 ====================

    """

    def RegisterNode(self, request, context):
        """RegisterNode 注册节点到全局注册中心
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck 节点健康检查，定期上报节点状态和资源使用情况
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=global_dot_registry_dot_registry__pb2.RegisterNodeRequest.FromString,
                    response_serializer=global_dot_registry_dot_registry__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=global_dot_registry_dot_registry__pb2.HealthCheckRequest.FromString,
                    response_serializer=global_dot_registry_dot_registry__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'global.registry.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('global.registry.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """==================== 服务定义 ====================

    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/global.registry.Service/RegisterNode',
            global_dot_registry_dot_registry__pb2.RegisterNodeRequest.SerializeToString,
            global_dot_registry_dot_registry__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/global.registry.Service/HealthCheck',
            global_dot_registry_dot_registry__pb2.HealthCheckRequest.SerializeToString,
            global_dot_registry_dot_registry__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
