// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: resource/discovery/discovery.proto

package discovery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryService_GossipNodeInfo_FullMethodName   = "/discovery.DiscoveryService/GossipNodeInfo"
	DiscoveryService_QueryResources_FullMethodName   = "/discovery.DiscoveryService/QueryResources"
	DiscoveryService_ExchangePeerList_FullMethodName = "/discovery.DiscoveryService/ExchangePeerList"
	DiscoveryService_GetLocalNodeInfo_FullMethodName = "/discovery.DiscoveryService/GetLocalNodeInfo"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	// GossipNodeInfo 交换节点信息（gossip 协议）
	GossipNodeInfo(ctx context.Context, in *NodeInfoGossipMessage, opts ...grpc.CallOption) (*NodeInfoGossipResponse, error)
	// QueryResources 查询资源（主动查询）
	QueryResources(ctx context.Context, in *ResourceQueryRequest, opts ...grpc.CallOption) (*ResourceQueryResponse, error)
	// ExchangePeerList 交换 peer 列表（用于节点发现）
	ExchangePeerList(ctx context.Context, in *PeerListExchangeRequest, opts ...grpc.CallOption) (*PeerListExchangeResponse, error)
	// GetLocalNodeInfo 获取本地节点信息（用于其他节点查询）
	GetLocalNodeInfo(ctx context.Context, in *GetLocalNodeInfoRequest, opts ...grpc.CallOption) (*GetLocalNodeInfoResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) GossipNodeInfo(ctx context.Context, in *NodeInfoGossipMessage, opts ...grpc.CallOption) (*NodeInfoGossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoGossipResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GossipNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) QueryResources(ctx context.Context, in *ResourceQueryRequest, opts ...grpc.CallOption) (*ResourceQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceQueryResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_QueryResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) ExchangePeerList(ctx context.Context, in *PeerListExchangeRequest, opts ...grpc.CallOption) (*PeerListExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerListExchangeResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_ExchangePeerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetLocalNodeInfo(ctx context.Context, in *GetLocalNodeInfoRequest, opts ...grpc.CallOption) (*GetLocalNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalNodeInfoResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GetLocalNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
type DiscoveryServiceServer interface {
	// GossipNodeInfo 交换节点信息（gossip 协议）
	GossipNodeInfo(context.Context, *NodeInfoGossipMessage) (*NodeInfoGossipResponse, error)
	// QueryResources 查询资源（主动查询）
	QueryResources(context.Context, *ResourceQueryRequest) (*ResourceQueryResponse, error)
	// ExchangePeerList 交换 peer 列表（用于节点发现）
	ExchangePeerList(context.Context, *PeerListExchangeRequest) (*PeerListExchangeResponse, error)
	// GetLocalNodeInfo 获取本地节点信息（用于其他节点查询）
	GetLocalNodeInfo(context.Context, *GetLocalNodeInfoRequest) (*GetLocalNodeInfoResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) GossipNodeInfo(context.Context, *NodeInfoGossipMessage) (*NodeInfoGossipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GossipNodeInfo not implemented")
}
func (UnimplementedDiscoveryServiceServer) QueryResources(context.Context, *ResourceQueryRequest) (*ResourceQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryResources not implemented")
}
func (UnimplementedDiscoveryServiceServer) ExchangePeerList(context.Context, *PeerListExchangeRequest) (*PeerListExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangePeerList not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetLocalNodeInfo(context.Context, *GetLocalNodeInfoRequest) (*GetLocalNodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalNodeInfo not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_GossipNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoGossipMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GossipNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GossipNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GossipNodeInfo(ctx, req.(*NodeInfoGossipMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_QueryResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).QueryResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_QueryResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).QueryResources(ctx, req.(*ResourceQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_ExchangePeerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerListExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).ExchangePeerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_ExchangePeerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).ExchangePeerList(ctx, req.(*PeerListExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetLocalNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetLocalNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetLocalNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetLocalNodeInfo(ctx, req.(*GetLocalNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GossipNodeInfo",
			Handler:    _DiscoveryService_GossipNodeInfo_Handler,
		},
		{
			MethodName: "QueryResources",
			Handler:    _DiscoveryService_QueryResources_Handler,
		},
		{
			MethodName: "ExchangePeerList",
			Handler:    _DiscoveryService_ExchangePeerList_Handler,
		},
		{
			MethodName: "GetLocalNodeInfo",
			Handler:    _DiscoveryService_GetLocalNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/discovery/discovery.proto",
}
