// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: global/registry/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatus 节点状态
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNKNOWN NodeStatus = 0 // 未知状态
	NodeStatus_NODE_STATUS_ONLINE  NodeStatus = 1 // 在线
	NodeStatus_NODE_STATUS_OFFLINE NodeStatus = 2 // 离线
	NodeStatus_NODE_STATUS_ERROR   NodeStatus = 3 // 错误
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNKNOWN",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_ERROR",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNKNOWN": 0,
		"NODE_STATUS_ONLINE":  1,
		"NODE_STATUS_OFFLINE": 2,
		"NODE_STATUS_ERROR":   3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_global_registry_registry_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_global_registry_registry_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{0}
}

// ProviderStatus Provider 状态
type ProviderStatus int32

const (
	ProviderStatus_PROVIDER_STATUS_UNKNOWN ProviderStatus = 0 // 未知状态
	ProviderStatus_PROVIDER_STATUS_RUNNING ProviderStatus = 1 // 运行中
	ProviderStatus_PROVIDER_STATUS_STOPPED ProviderStatus = 2 // 已停止
	ProviderStatus_PROVIDER_STATUS_ERROR   ProviderStatus = 3 // 错误
)

// Enum value maps for ProviderStatus.
var (
	ProviderStatus_name = map[int32]string{
		0: "PROVIDER_STATUS_UNKNOWN",
		1: "PROVIDER_STATUS_RUNNING",
		2: "PROVIDER_STATUS_STOPPED",
		3: "PROVIDER_STATUS_ERROR",
	}
	ProviderStatus_value = map[string]int32{
		"PROVIDER_STATUS_UNKNOWN": 0,
		"PROVIDER_STATUS_RUNNING": 1,
		"PROVIDER_STATUS_STOPPED": 2,
		"PROVIDER_STATUS_ERROR":   3,
	}
)

func (x ProviderStatus) Enum() *ProviderStatus {
	p := new(ProviderStatus)
	*p = x
	return p
}

func (x ProviderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_global_registry_registry_proto_enumTypes[1].Descriptor()
}

func (ProviderStatus) Type() protoreflect.EnumType {
	return &file_global_registry_registry_proto_enumTypes[1]
}

func (x ProviderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderStatus.Descriptor instead.
func (ProviderStatus) EnumDescriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{1}
}

type RegisterNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DomainId        string                 `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName        string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeDescription string                 `protobuf:"bytes,4,opt,name=node_description,json=nodeDescription,proto3" json:"node_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_global_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterNodeRequest) GetNodeDescription() string {
	if x != nil {
		return x.NodeDescription
	}
	return ""
}

type RegisterNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DomainName        string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	DomainDescription string                 `protobuf:"bytes,2,opt,name=domain_description,json=domainDescription,proto3" json:"domain_description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_global_registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *RegisterNodeResponse) GetDomainDescription() string {
	if x != nil {
		return x.DomainDescription
	}
	return ""
}

// ResourceInfo 资源信息
type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // CPU millicores (毫核)
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // Memory bytes (字节)
	Gpu           int64                  `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`       // GPU count (数量)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_global_registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceInfo) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ResourceInfo) GetGpu() int64 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

// ResourceCapacity 资源容量（总容量、已使用、可用）
type ResourceCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *ResourceInfo          `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`         // 总资源
	Used          *ResourceInfo          `protobuf:"bytes,2,opt,name=used,proto3" json:"used,omitempty"`           // 已使用资源
	Available     *ResourceInfo          `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"` // 可用资源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCapacity) Reset() {
	*x = ResourceCapacity{}
	mi := &file_global_registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapacity) ProtoMessage() {}

func (x *ResourceCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapacity.ProtoReflect.Descriptor instead.
func (*ResourceCapacity) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceCapacity) GetTotal() *ResourceInfo {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *ResourceCapacity) GetUsed() *ResourceInfo {
	if x != nil {
		return x.Used
	}
	return nil
}

func (x *ResourceCapacity) GetAvailable() *ResourceInfo {
	if x != nil {
		return x.Available
	}
	return nil
}

// ResourceTags 资源标签（描述节点支持的计算资源类型）
type ResourceTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           bool                   `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // 是否支持 CPU
	Gpu           bool                   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`       // 是否支持 GPU
	Memory        bool                   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"` // 是否支持内存
	Camera        bool                   `protobuf:"varint,4,opt,name=camera,proto3" json:"camera,omitempty"` // 是否支持摄像头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTags) Reset() {
	*x = ResourceTags{}
	mi := &file_global_registry_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTags) ProtoMessage() {}

func (x *ResourceTags) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTags.ProtoReflect.Descriptor instead.
func (*ResourceTags) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceTags) GetCpu() bool {
	if x != nil {
		return x.Cpu
	}
	return false
}

func (x *ResourceTags) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *ResourceTags) GetMemory() bool {
	if x != nil {
		return x.Memory
	}
	return false
}

func (x *ResourceTags) GetCamera() bool {
	if x != nil {
		return x.Camera
	}
	return false
}

// ProviderInfo Provider 信息
type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Provider ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Provider 名称
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // Provider 类型 (compute/storage/gpu/network/cloud 等)
	Status        ProviderStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=global.registry.ProviderStatus" json:"status,omitempty"`                                          // Provider 状态
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Provider 版本
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_global_registry_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderInfo) GetStatus() ProviderStatus {
	if x != nil {
		return x.Status
	}
	return ProviderStatus_PROVIDER_STATUS_UNKNOWN
}

func (x *ProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                               // 节点 ID
	DomainId         string                 `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`                         // 域 ID
	Status           NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=global.registry.NodeStatus" json:"status,omitempty"`            // 节点状态
	ResourceCapacity *ResourceCapacity      `protobuf:"bytes,4,opt,name=resource_capacity,json=resourceCapacity,proto3" json:"resource_capacity,omitempty"` // 资源容量信息
	ResourceTags     *ResourceTags          `protobuf:"bytes,5,opt,name=resource_tags,json=resourceTags,proto3" json:"resource_tags,omitempty"`             // 资源标签
	Address          string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`                                           // 节点地址 (host:port)
	Timestamp        int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // 时间戳 (Unix nanoseconds)
	IsHead           bool                   `protobuf:"varint,8,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"`                              // 是否为 head 节点（已废弃，保留兼容）
	Providers        []*ProviderInfo        `protobuf:"bytes,9,rep,name=providers,proto3" json:"providers,omitempty"`                                       // 本地 Provider 信息列表
	NodeName         string                 `protobuf:"bytes,10,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                        // 节点名称
	NodeDescription  string                 `protobuf:"bytes,11,opt,name=node_description,json=nodeDescription,proto3" json:"node_description,omitempty"`   // 节点描述
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_global_registry_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckRequest) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *HealthCheckRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNKNOWN
}

func (x *HealthCheckRequest) GetResourceCapacity() *ResourceCapacity {
	if x != nil {
		return x.ResourceCapacity
	}
	return nil
}

func (x *HealthCheckRequest) GetResourceTags() *ResourceTags {
	if x != nil {
		return x.ResourceTags
	}
	return nil
}

func (x *HealthCheckRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HealthCheckRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckRequest) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *HealthCheckRequest) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *HealthCheckRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthCheckRequest) GetNodeDescription() string {
	if x != nil {
		return x.NodeDescription
	}
	return ""
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestamp            int64                  `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`                                    // 服务器时间戳 (Unix nanoseconds)
	RecommendedIntervalSeconds int32                  `protobuf:"varint,2,opt,name=recommended_interval_seconds,json=recommendedIntervalSeconds,proto3" json:"recommended_interval_seconds,omitempty"` // 建议健康检查间隔（秒）
	RequireReregister          bool                   `protobuf:"varint,3,opt,name=require_reregister,json=requireReregister,proto3" json:"require_reregister,omitempty"`                              // 是否需要重新注册
	StatusCode                 string                 `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                    // 状态码：success/warning/error
	Message                    string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                            // 可选消息
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_global_registry_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_global_registry_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_global_registry_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetRecommendedIntervalSeconds() int32 {
	if x != nil {
		return x.RecommendedIntervalSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetRequireReregister() bool {
	if x != nil {
		return x.RequireReregister
	}
	return false
}

func (x *HealthCheckResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_global_registry_registry_proto protoreflect.FileDescriptor

const file_global_registry_registry_proto_rawDesc = "" +
	"\n" +
	"\x1eglobal/registry/registry.proto\x12\x0fglobal.registry\"\x93\x01\n" +
	"\x13RegisterNodeRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\tR\bdomainId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12)\n" +
	"\x10node_description\x18\x04 \x01(\tR\x0fnodeDescription\"f\n" +
	"\x14RegisterNodeResponse\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12-\n" +
	"\x12domain_description\x18\x02 \x01(\tR\x11domainDescription\"J\n" +
	"\fResourceInfo\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x03R\x03gpu\"\xb7\x01\n" +
	"\x10ResourceCapacity\x123\n" +
	"\x05total\x18\x01 \x01(\v2\x1d.global.registry.ResourceInfoR\x05total\x121\n" +
	"\x04used\x18\x02 \x01(\v2\x1d.global.registry.ResourceInfoR\x04used\x12;\n" +
	"\tavailable\x18\x03 \x01(\v2\x1d.global.registry.ResourceInfoR\tavailable\"b\n" +
	"\fResourceTags\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\bR\x03cpu\x12\x10\n" +
	"\x03gpu\x18\x02 \x01(\bR\x03gpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\bR\x06memory\x12\x16\n" +
	"\x06camera\x18\x04 \x01(\bR\x06camera\"\x9f\x02\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.global.registry.ProviderStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.global.registry.ProviderInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x03\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\tR\bdomainId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.global.registry.NodeStatusR\x06status\x12N\n" +
	"\x11resource_capacity\x18\x04 \x01(\v2!.global.registry.ResourceCapacityR\x10resourceCapacity\x12B\n" +
	"\rresource_tags\x18\x05 \x01(\v2\x1d.global.registry.ResourceTagsR\fresourceTags\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x17\n" +
	"\ais_head\x18\b \x01(\bR\x06isHead\x12;\n" +
	"\tproviders\x18\t \x03(\v2\x1d.global.registry.ProviderInfoR\tproviders\x12\x1b\n" +
	"\tnode_name\x18\n" +
	" \x01(\tR\bnodeName\x12)\n" +
	"\x10node_description\x18\v \x01(\tR\x0fnodeDescription\"\xec\x01\n" +
	"\x13HealthCheckResponse\x12)\n" +
	"\x10server_timestamp\x18\x01 \x01(\x03R\x0fserverTimestamp\x12@\n" +
	"\x1crecommended_interval_seconds\x18\x02 \x01(\x05R\x1arecommendedIntervalSeconds\x12-\n" +
	"\x12require_reregister\x18\x03 \x01(\bR\x11requireReregister\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*m\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x15\n" +
	"\x11NODE_STATUS_ERROR\x10\x03*\x82\x01\n" +
	"\x0eProviderStatus\x12\x1b\n" +
	"\x17PROVIDER_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17PROVIDER_STATUS_RUNNING\x10\x01\x12\x1b\n" +
	"\x17PROVIDER_STATUS_STOPPED\x10\x02\x12\x19\n" +
	"\x15PROVIDER_STATUS_ERROR\x10\x032\xc0\x01\n" +
	"\aService\x12[\n" +
	"\fRegisterNode\x12$.global.registry.RegisterNodeRequest\x1a%.global.registry.RegisterNodeResponse\x12X\n" +
	"\vHealthCheck\x12#.global.registry.HealthCheckRequest\x1a$.global.registry.HealthCheckResponseB:Z8github.com/9triver/iarnet/internal/proto/global/registryb\x06proto3"

var (
	file_global_registry_registry_proto_rawDescOnce sync.Once
	file_global_registry_registry_proto_rawDescData []byte
)

func file_global_registry_registry_proto_rawDescGZIP() []byte {
	file_global_registry_registry_proto_rawDescOnce.Do(func() {
		file_global_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_global_registry_registry_proto_rawDesc), len(file_global_registry_registry_proto_rawDesc)))
	})
	return file_global_registry_registry_proto_rawDescData
}

var file_global_registry_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_global_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_global_registry_registry_proto_goTypes = []any{
	(NodeStatus)(0),              // 0: global.registry.NodeStatus
	(ProviderStatus)(0),          // 1: global.registry.ProviderStatus
	(*RegisterNodeRequest)(nil),  // 2: global.registry.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 3: global.registry.RegisterNodeResponse
	(*ResourceInfo)(nil),         // 4: global.registry.ResourceInfo
	(*ResourceCapacity)(nil),     // 5: global.registry.ResourceCapacity
	(*ResourceTags)(nil),         // 6: global.registry.ResourceTags
	(*ProviderInfo)(nil),         // 7: global.registry.ProviderInfo
	(*HealthCheckRequest)(nil),   // 8: global.registry.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 9: global.registry.HealthCheckResponse
	nil,                          // 10: global.registry.ProviderInfo.MetadataEntry
}
var file_global_registry_registry_proto_depIdxs = []int32{
	4,  // 0: global.registry.ResourceCapacity.total:type_name -> global.registry.ResourceInfo
	4,  // 1: global.registry.ResourceCapacity.used:type_name -> global.registry.ResourceInfo
	4,  // 2: global.registry.ResourceCapacity.available:type_name -> global.registry.ResourceInfo
	1,  // 3: global.registry.ProviderInfo.status:type_name -> global.registry.ProviderStatus
	10, // 4: global.registry.ProviderInfo.metadata:type_name -> global.registry.ProviderInfo.MetadataEntry
	0,  // 5: global.registry.HealthCheckRequest.status:type_name -> global.registry.NodeStatus
	5,  // 6: global.registry.HealthCheckRequest.resource_capacity:type_name -> global.registry.ResourceCapacity
	6,  // 7: global.registry.HealthCheckRequest.resource_tags:type_name -> global.registry.ResourceTags
	7,  // 8: global.registry.HealthCheckRequest.providers:type_name -> global.registry.ProviderInfo
	2,  // 9: global.registry.Service.RegisterNode:input_type -> global.registry.RegisterNodeRequest
	8,  // 10: global.registry.Service.HealthCheck:input_type -> global.registry.HealthCheckRequest
	3,  // 11: global.registry.Service.RegisterNode:output_type -> global.registry.RegisterNodeResponse
	9,  // 12: global.registry.Service.HealthCheck:output_type -> global.registry.HealthCheckResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_global_registry_registry_proto_init() }
func file_global_registry_registry_proto_init() {
	if File_global_registry_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_global_registry_registry_proto_rawDesc), len(file_global_registry_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_global_registry_registry_proto_goTypes,
		DependencyIndexes: file_global_registry_registry_proto_depIdxs,
		EnumInfos:         file_global_registry_registry_proto_enumTypes,
		MessageInfos:      file_global_registry_registry_proto_msgTypes,
	}.Build()
	File_global_registry_registry_proto = out.File
	file_global_registry_registry_proto_goTypes = nil
	file_global_registry_registry_proto_depIdxs = nil
}
